// california-fqhcs.ts
// Comprehensive directory of California Federally Qualified Health Centers (FQHCs)

export interface CaliforniaFQHC {
  name: string;
  slug: string;
  city: string;
  county: string;
  region:
    | "Los Angeles"
    | "San Diego"
    | "Bay Area"
    | "Sacramento"
    | "Central Valley"
    | "Inland Empire"
    | "Other";
  lat: number;
  lng: number;
  siteCount: number;
  patientCount: string;
  programs: string[];
  ehrSystem: string;
  website: string;
  description: string;
}

export const regions = [
  "Los Angeles",
  "San Diego",
  "Bay Area",
  "Sacramento",
  "Central Valley",
  "Inland Empire",
  "Other",
] as const;

export const allPrograms = [
  "ECM",
  "CCM",
  "Community Supports",
  "BH Integration",
  "TCM",
  "BH-ASO",
] as const;

export const allEhrSystems = [
  "OCHIN Epic",
  "NextGen",
  "eClinicalWorks",
  "Cerner",
  "athenahealth",
  "Other",
] as const;

export const californiaFQHCs: CaliforniaFQHC[] = [
  // ─────────────────────────────────────────────
  // LOS ANGELES REGION (15)
  // ─────────────────────────────────────────────
  {
    name: "AltaMed Health Services",
    slug: "altamed-health-services",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0244,
    lng: -118.1728,
    siteCount: 50,
    patientCount: "300,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.altamed.org",
    description:
      "One of the largest FQHCs in the nation, AltaMed serves over 300,000 patients across Los Angeles and Orange counties with comprehensive primary care, dental, behavioral health, and senior services.",
  },
  {
    name: "APLA Health",
    slug: "apla-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0901,
    lng: -118.3617,
    siteCount: 8,
    patientCount: "15,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://aplahealth.org",
    description:
      "APLA Health provides comprehensive medical, dental, behavioral health, and HIV specialty care with a focus on LGBTQ+ communities and underserved populations in Los Angeles.",
  },
  {
    name: "ChapCare",
    slug: "chapcare",
    city: "Pasadena",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.1478,
    lng: -118.1445,
    siteCount: 6,
    patientCount: "30,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.chapcare.org",
    description:
      "ChapCare is a nonprofit community health center providing primary care, dental, vision, and behavioral health services to families in the San Gabriel Valley and greater Pasadena area.",
  },
  {
    name: "Eisner Health",
    slug: "eisner-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0359,
    lng: -118.2595,
    siteCount: 7,
    patientCount: "50,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.eisnerhealth.org",
    description:
      "Founded in 1920, Eisner Health offers comprehensive primary care, women's health, pediatrics, dental, and behavioral health services in downtown Los Angeles and surrounding communities.",
  },
  {
    name: "JWCH Institute",
    slug: "jwch-institute",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0453,
    lng: -118.2468,
    siteCount: 12,
    patientCount: "60,000+",
    programs: ["ECM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.jwchinstitute.org",
    description:
      "JWCH Institute provides health care and related services for homeless and underserved individuals in Los Angeles County, including HIV/AIDS care, substance use treatment, and primary care.",
  },
  {
    name: "Los Angeles Christian Health Centers",
    slug: "los-angeles-christian-health-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0435,
    lng: -118.2453,
    siteCount: 4,
    patientCount: "12,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.lachc.com",
    description:
      "Los Angeles Christian Health Centers offers compassionate, high-quality medical and dental care to those experiencing homelessness and poverty on Skid Row and surrounding neighborhoods.",
  },
  {
    name: "Northeast Valley Health Corporation",
    slug: "northeast-valley-health-corporation",
    city: "San Fernando",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.2819,
    lng: -118.439,
    siteCount: 14,
    patientCount: "85,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nevhc.org",
    description:
      "Northeast Valley Health Corporation operates 14 health centers across the San Fernando and Santa Clarita Valleys, providing primary care, dental, OB/GYN, and behavioral health services.",
  },
  {
    name: "South Central Family Health Center",
    slug: "south-central-family-health-center",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9925,
    lng: -118.2551,
    siteCount: 4,
    patientCount: "25,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.scfhc.org",
    description:
      "South Central Family Health Center provides culturally competent medical, dental, and behavioral health services to predominantly Latino and African American communities in South Los Angeles.",
  },
  {
    name: "St. John's Community Health",
    slug: "st-johns-community-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0528,
    lng: -118.2442,
    siteCount: 18,
    patientCount: "100,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.wellchild.org",
    description:
      "St. John's Community Health is one of the largest community health center networks in Los Angeles, providing comprehensive primary care, dental, and wellness services to underserved communities.",
  },
  {
    name: "T.H.E. Health and Wellness Centers",
    slug: "the-health-and-wellness-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9831,
    lng: -118.3064,
    siteCount: 5,
    patientCount: "20,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.thehealthandwellness.org",
    description:
      "T.H.E. Health and Wellness Centers is a women-founded organization providing comprehensive health services to underserved communities in South Los Angeles, with a focus on women and children.",
  },
  {
    name: "Venice Family Clinic",
    slug: "venice-family-clinic",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9962,
    lng: -118.4628,
    siteCount: 14,
    patientCount: "45,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://venicefamilyclinic.org",
    description:
      "Venice Family Clinic is the largest free clinic in the nation, providing quality primary care, dental, mental health, and specialty services to people in need across the Westside and South Bay.",
  },
  {
    name: "Watts Healthcare Corporation",
    slug: "watts-healthcare-corporation",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9425,
    lng: -118.2451,
    siteCount: 3,
    patientCount: "18,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.wattshealth.org",
    description:
      "Watts Healthcare Corporation has served the Watts community since 1967, providing primary care, dental, behavioral health, and HIV services to one of Los Angeles County's most underserved areas.",
  },
  {
    name: "Herald Christian Health Center",
    slug: "herald-christian-health-center",
    city: "Rosemead",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0806,
    lng: -118.073,
    siteCount: 3,
    patientCount: "22,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.heraldhealth.org",
    description:
      "Herald Christian Health Center provides culturally and linguistically appropriate medical, dental, and behavioral health services to Asian and Pacific Islander communities in the San Gabriel Valley.",
  },
  {
    name: "Community Health Alliance of Pasadena",
    slug: "community-health-alliance-of-pasadena",
    city: "Pasadena",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.1473,
    lng: -118.1312,
    siteCount: 5,
    patientCount: "20,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.chaphealth.org",
    description:
      "Community Health Alliance of Pasadena (CHAP) delivers high-quality primary care, behavioral health, and dental services to the diverse communities of Pasadena and surrounding areas.",
  },
  {
    name: "UMMA Community Clinic",
    slug: "umma-community-clinic",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9878,
    lng: -118.2999,
    siteCount: 2,
    patientCount: "10,000+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.ummaclinic.org",
    description:
      "UMMA Community Clinic provides high-quality health care to South Los Angeles, promoting a health model that combines medicine with neighborhood-level community development and wellness.",
  },

  // ─────────────────────────────────────────────
  // SAN DIEGO REGION (8)
  // ─────────────────────────────────────────────
  {
    name: "Family Health Centers of San Diego",
    slug: "family-health-centers-of-san-diego",
    city: "San Diego",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7157,
    lng: -117.1611,
    siteCount: 47,
    patientCount: "227,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.fhcsd.org",
    description:
      "Family Health Centers of San Diego is the region's largest FQHC, providing medical, dental, behavioral health, HIV services, and housing support across 47 sites throughout San Diego County.",
  },
  {
    name: "La Maestra Community Health Centers",
    slug: "la-maestra-community-health-centers",
    city: "San Diego",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7716,
    lng: -117.0643,
    siteCount: 10,
    patientCount: "80,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.lamaestra.org",
    description:
      "La Maestra Community Health Centers serves the refugee and immigrant communities of City Heights and surrounding San Diego neighborhoods with culturally competent comprehensive health care.",
  },
  {
    name: "San Ysidro Health",
    slug: "san-ysidro-health",
    city: "San Ysidro",
    county: "San Diego",
    region: "San Diego",
    lat: 32.5556,
    lng: -117.0462,
    siteCount: 35,
    patientCount: "113,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.syhealth.org",
    description:
      "San Ysidro Health is one of the largest FQHCs in the nation, providing medical, dental, behavioral health, chiropractic, and optometry services to communities along the U.S.-Mexico border.",
  },
  {
    name: "Neighborhood Healthcare",
    slug: "neighborhood-healthcare",
    city: "Escondido",
    county: "San Diego",
    region: "San Diego",
    lat: 33.1192,
    lng: -117.0864,
    siteCount: 19,
    patientCount: "90,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nhcare.org",
    description:
      "Neighborhood Healthcare provides comprehensive medical, dental, behavioral health, and specialty care at 19 sites across San Diego and Riverside counties.",
  },
  {
    name: "Vista Community Clinic",
    slug: "vista-community-clinic",
    city: "Vista",
    county: "San Diego",
    region: "San Diego",
    lat: 33.2003,
    lng: -117.2425,
    siteCount: 8,
    patientCount: "65,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.vistacommunityclinic.org",
    description:
      "Vista Community Clinic provides affordable primary care, pediatrics, prenatal, dental, and behavioral health services to North San Diego County communities.",
  },
  {
    name: "Mountain Health and Community Services",
    slug: "mountain-health-and-community-services",
    city: "Lake Cuyamaca",
    county: "San Diego",
    region: "San Diego",
    lat: 32.9888,
    lng: -116.5739,
    siteCount: 3,
    patientCount: "8,000+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "athenahealth",
    website: "https://www.mtnhealth.org",
    description:
      "Mountain Health and Community Services provides primary care and community services to rural and frontier communities in the mountain regions of eastern San Diego County.",
  },
  {
    name: "Borrego Health - San Diego",
    slug: "borrego-health-san-diego",
    city: "El Cajon",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7948,
    lng: -116.9625,
    siteCount: 6,
    patientCount: "35,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.borregohealth.org",
    description:
      "Borrego Health's San Diego sites provide comprehensive medical, dental, and behavioral health care to diverse communities across East County San Diego.",
  },
  {
    name: "Imperial Beach Health Center",
    slug: "imperial-beach-health-center",
    city: "Imperial Beach",
    county: "San Diego",
    region: "San Diego",
    lat: 32.584,
    lng: -117.1131,
    siteCount: 2,
    patientCount: "12,000+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.ibhealthcenter.org",
    description:
      "Imperial Beach Health Center delivers primary care, prenatal, and pediatric services to the southernmost coastal community in San Diego County near the U.S.-Mexico border.",
  },

  // ─────────────────────────────────────────────
  // BAY AREA REGION (10)
  // ─────────────────────────────────────────────
  {
    name: "LifeLong Medical Care",
    slug: "lifelong-medical-care",
    city: "Berkeley",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8702,
    lng: -122.2728,
    siteCount: 15,
    patientCount: "66,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.lifelongmedical.org",
    description:
      "LifeLong Medical Care provides comprehensive health and social services to underserved people of all ages throughout the East Bay, including medical, dental, behavioral health, and homeless services.",
  },
  {
    name: "Asian Health Services",
    slug: "asian-health-services",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.7985,
    lng: -122.2711,
    siteCount: 5,
    patientCount: "50,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.asianhealthservices.org",
    description:
      "Asian Health Services provides medical, dental, behavioral health, and enabling services in over 14 languages to the diverse Asian communities in Oakland's Chinatown and beyond.",
  },
  {
    name: "La Clinica de La Raza",
    slug: "la-clinica-de-la-raza",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.7807,
    lng: -122.2228,
    siteCount: 35,
    patientCount: "90,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.laclinica.org",
    description:
      "La Clinica de La Raza is a leading community health center network offering culturally appropriate medical, dental, behavioral health, and optometry services across the East Bay and Contra Costa County.",
  },
  {
    name: "North East Medical Services",
    slug: "north-east-medical-services",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7941,
    lng: -122.4078,
    siteCount: 9,
    patientCount: "45,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nems.org",
    description:
      "North East Medical Services is a nonprofit community health center providing multilingual primary care, dental, behavioral health, and specialty services to Asian American communities in San Francisco.",
  },
  {
    name: "Ravenswood Family Health Network",
    slug: "ravenswood-family-health-network",
    city: "East Palo Alto",
    county: "San Mateo",
    region: "Bay Area",
    lat: 37.4688,
    lng: -122.1411,
    siteCount: 5,
    patientCount: "20,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.ravenswoodfhn.org",
    description:
      "Ravenswood Family Health Network provides comprehensive primary care, dental, and behavioral health services to underserved communities on the San Francisco Peninsula, including East Palo Alto and Belle Haven.",
  },
  {
    name: "Gardner Health Services",
    slug: "gardner-health-services",
    city: "San Jose",
    county: "Santa Clara",
    region: "Bay Area",
    lat: 37.3293,
    lng: -121.8894,
    siteCount: 9,
    patientCount: "42,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.gardnerhealthservices.org",
    description:
      "Gardner Health Services provides culturally sensitive primary care, dental, behavioral health, and specialty care to diverse communities in Santa Clara County, including migrant and seasonal farmworkers.",
  },
  {
    name: "San Francisco Community Health Center",
    slug: "san-francisco-community-health-center",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7849,
    lng: -122.4094,
    siteCount: 5,
    patientCount: "15,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.sfcommunityhealth.org",
    description:
      "San Francisco Community Health Center provides culturally competent primary care, behavioral health, and transgender health services with a focus on Asian and Pacific Islander and LGBTQ+ communities.",
  },
  {
    name: "Native American Health Center",
    slug: "native-american-health-center",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8044,
    lng: -122.2712,
    siteCount: 4,
    patientCount: "14,000+",
    programs: ["ECM", "BH Integration", "Community Supports", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.nativehealth.org",
    description:
      "Native American Health Center provides comprehensive medical, dental, behavioral health, and traditional healing services to Native American and underserved communities in Oakland and San Francisco.",
  },
  {
    name: "Tiburcio Vasquez Health Center",
    slug: "tiburcio-vasquez-health-center",
    city: "Hayward",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.6688,
    lng: -122.0808,
    siteCount: 8,
    patientCount: "35,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.tvhc.org",
    description:
      "Tiburcio Vasquez Health Center offers primary care, dental, optometry, behavioral health, and women's health services to underserved communities across southern Alameda County.",
  },
  {
    name: "Axis Community Health",
    slug: "axis-community-health",
    city: "Pleasanton",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.6624,
    lng: -121.8747,
    siteCount: 4,
    patientCount: "16,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.axishealth.org",
    description:
      "Axis Community Health provides primary medical care, behavioral health, and substance use treatment to families in the Tri-Valley area of eastern Alameda County.",
  },

  // ─────────────────────────────────────────────
  // SACRAMENTO REGION (5)
  // ─────────────────────────────────────────────
  {
    name: "WellSpace Health",
    slug: "wellspace-health",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5816,
    lng: -121.4944,
    siteCount: 17,
    patientCount: "70,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.wellspacehealth.org",
    description:
      "WellSpace Health is the Sacramento region's largest FQHC, providing primary care, dental, behavioral health, addiction medicine, and crisis services across 17 locations.",
  },
  {
    name: "Sacramento Native American Health Center",
    slug: "sacramento-native-american-health-center",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5649,
    lng: -121.4687,
    siteCount: 3,
    patientCount: "12,000+",
    programs: ["ECM", "BH Integration", "Community Supports", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.snahc.org",
    description:
      "Sacramento Native American Health Center provides culturally responsive medical, dental, behavioral health, and traditional healing services to Native American and other underserved communities.",
  },
  {
    name: "Elica Health Centers",
    slug: "elica-health-centers",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5961,
    lng: -121.4404,
    siteCount: 7,
    patientCount: "45,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.elicahealth.org",
    description:
      "Elica Health Centers provides primary care, dental, behavioral health, and pharmacy services to Sacramento's diverse refugee and immigrant communities in over 40 languages.",
  },
  {
    name: "CommuniCare Health Centers",
    slug: "communicare-health-centers",
    city: "Davis",
    county: "Yolo",
    region: "Sacramento",
    lat: 38.5449,
    lng: -121.7405,
    siteCount: 8,
    patientCount: "38,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.communicarehc.org",
    description:
      "CommuniCare Health Centers provides comprehensive medical, dental, and behavioral health services to underserved communities across Yolo County, including Davis, Woodland, and West Sacramento.",
  },
  {
    name: "One Community Health",
    slug: "one-community-health",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5752,
    lng: -121.4689,
    siteCount: 5,
    patientCount: "25,000+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.onecommunityhealth.com",
    description:
      "One Community Health provides affirming primary care, sexual health, behavioral health, and pharmacy services with a focus on LGBTQ+ communities and people living with HIV in the Sacramento area.",
  },

  // ─────────────────────────────────────────────
  // CENTRAL VALLEY REGION (7)
  // ─────────────────────────────────────────────
  {
    name: "Clinica Sierra Vista",
    slug: "clinica-sierra-vista",
    city: "Bakersfield",
    county: "Kern",
    region: "Central Valley",
    lat: 35.3733,
    lng: -119.0187,
    siteCount: 38,
    patientCount: "200,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.clinicasierravista.org",
    description:
      "Clinica Sierra Vista is the largest FQHC in Kern County and one of the largest in California, operating 38 sites providing medical, dental, behavioral health, and WIC services.",
  },
  {
    name: "United Health Centers",
    slug: "united-health-centers",
    city: "Parlier",
    county: "Fresno",
    region: "Central Valley",
    lat: 36.6117,
    lng: -119.5271,
    siteCount: 22,
    patientCount: "120,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.unitedhealthcenters.org",
    description:
      "United Health Centers provides comprehensive medical, dental, optometry, and behavioral health care to agricultural communities across Fresno, Kings, and Tulare counties in the San Joaquin Valley.",
  },
  {
    name: "Family HealthCare Network",
    slug: "family-healthcare-network",
    city: "Visalia",
    county: "Tulare",
    region: "Central Valley",
    lat: 36.3302,
    lng: -119.2921,
    siteCount: 45,
    patientCount: "175,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.fhcn.org",
    description:
      "Family HealthCare Network operates 45 sites across Tulare and Kings counties, providing primary care, dental, behavioral health, and pharmacy services primarily to farmworker families.",
  },
  {
    name: "Camarena Health",
    slug: "camarena-health",
    city: "Madera",
    county: "Madera",
    region: "Central Valley",
    lat: 36.9613,
    lng: -120.0607,
    siteCount: 7,
    patientCount: "45,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.camarenahealth.org",
    description:
      "Camarena Health provides primary care, dental, optometry, and behavioral health services to the agricultural communities of Madera County in California's Central Valley.",
  },
  {
    name: "Golden Valley Health Centers",
    slug: "golden-valley-health-centers",
    city: "Merced",
    county: "Merced",
    region: "Central Valley",
    lat: 37.3022,
    lng: -120.483,
    siteCount: 14,
    patientCount: "75,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.gvhc.org",
    description:
      "Golden Valley Health Centers serves Merced and Stanislaus counties with comprehensive medical, dental, behavioral health, and pediatric specialty services in California's Central Valley.",
  },
  {
    name: "Omni Family Health",
    slug: "omni-family-health",
    city: "Bakersfield",
    county: "Kern",
    region: "Central Valley",
    lat: 35.3732,
    lng: -119.0188,
    siteCount: 26,
    patientCount: "100,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.omnifamilyhealth.org",
    description:
      "Omni Family Health operates 26 health centers across Kern, Los Angeles, and San Bernardino counties, providing medical, dental, and behavioral health services to underserved communities.",
  },
  {
    name: "Livingston Community Health",
    slug: "livingston-community-health",
    city: "Livingston",
    county: "Merced",
    region: "Central Valley",
    lat: 37.3866,
    lng: -120.7231,
    siteCount: 4,
    patientCount: "18,000+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.livingstoncommhealth.org",
    description:
      "Livingston Community Health provides primary care, dental, and behavioral health services to the rural agricultural communities of the northern San Joaquin Valley in Merced County.",
  },

  // ─────────────────────────────────────────────
  // INLAND EMPIRE REGION (7)
  // ─────────────────────────────────────────────
  {
    name: "Borrego Health",
    slug: "borrego-health",
    city: "Brawley",
    county: "Imperial",
    region: "Inland Empire",
    lat: 32.9787,
    lng: -115.5303,
    siteCount: 28,
    patientCount: "150,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.borregohealth.org",
    description:
      "Borrego Health is one of the largest FQHCs in California, providing medical, dental, and behavioral health services across Imperial, Riverside, and San Bernardino counties and the Coachella Valley.",
  },
  {
    name: "SAC Health",
    slug: "sac-health",
    city: "San Bernardino",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.1083,
    lng: -117.2898,
    siteCount: 10,
    patientCount: "60,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.sachealthsystem.org",
    description:
      "SAC Health provides comprehensive primary care, dental, behavioral health, and pediatric specialty services to underserved communities throughout San Bernardino County's Inland Empire.",
  },
  {
    name: "Desert Healthcare District & Foundation",
    slug: "desert-healthcare-district",
    city: "Palm Springs",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.8303,
    lng: -116.5453,
    siteCount: 4,
    patientCount: "25,000+",
    programs: ["ECM", "Community Supports", "BH Integration"],
    ehrSystem: "athenahealth",
    website: "https://www.dhcd.org",
    description:
      "Desert Healthcare District supports access to health and wellness services in the eastern Coachella Valley, funding community health programs and providing primary care in the desert region.",
  },
  {
    name: "Riverside University Health System - Community Health Centers",
    slug: "riverside-university-health-system-chc",
    city: "Riverside",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.9533,
    lng: -117.3962,
    siteCount: 12,
    patientCount: "80,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "Cerner",
    website: "https://www.ruhealth.org",
    description:
      "Riverside University Health System's Community Health Centers provide medical, dental, behavioral health, and public health services at 12 locations throughout Riverside County.",
  },
  {
    name: "Loma Linda University Health - SAC Health",
    slug: "loma-linda-university-health-sac",
    city: "Loma Linda",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.0483,
    lng: -117.2613,
    siteCount: 6,
    patientCount: "35,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "Cerner",
    website: "https://www.lluh.org",
    description:
      "Loma Linda University Health's community health programs provide primary care, preventive services, and specialty care access to underserved populations in the Inland Empire.",
  },
  {
    name: "Community Health Systems, Inc.",
    slug: "community-health-systems-inc",
    city: "Riverside",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.9805,
    lng: -117.3755,
    siteCount: 9,
    patientCount: "55,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.chsica.org",
    description:
      "Community Health Systems provides medical, dental, and behavioral health services at multiple sites in Riverside and San Bernardino counties, serving diverse Inland Empire communities.",
  },
  {
    name: "Inland Faculty Medical Group",
    slug: "inland-faculty-medical-group",
    city: "Colton",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.0739,
    lng: -117.3137,
    siteCount: 5,
    patientCount: "30,000+",
    programs: ["ECM", "BH Integration", "CCM"],
    ehrSystem: "Cerner",
    website: "https://www.arrowheadmedcenter.org",
    description:
      "Inland Faculty Medical Group operates community health sites affiliated with Arrowhead Regional Medical Center, providing primary care and specialty services in San Bernardino County.",
  },

  // ─────────────────────────────────────────────
  // OTHER REGIONS (4)
  // ─────────────────────────────────────────────
  {
    name: "Community Health Centers of the Central Coast",
    slug: "community-health-centers-central-coast",
    city: "Santa Maria",
    county: "Santa Barbara",
    region: "Other",
    lat: 34.9531,
    lng: -120.4357,
    siteCount: 15,
    patientCount: "75,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.chccc.org",
    description:
      "Community Health Centers of the Central Coast provides primary care, dental, behavioral health, and pharmacy services to agricultural communities across Santa Barbara and San Luis Obispo counties.",
  },
  {
    name: "Shasta Community Health Center",
    slug: "shasta-community-health-center",
    city: "Redding",
    county: "Shasta",
    region: "Other",
    lat: 40.5865,
    lng: -122.3917,
    siteCount: 6,
    patientCount: "35,000+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.shastahealth.org",
    description:
      "Shasta Community Health Center provides comprehensive medical, dental, and behavioral health care to residents of the rural Northern California communities in Shasta County.",
  },
  {
    name: "Peach Tree Health",
    slug: "peach-tree-health",
    city: "Marysville",
    county: "Yuba",
    region: "Other",
    lat: 39.1457,
    lng: -121.5908,
    siteCount: 6,
    patientCount: "32,000+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.peachtreehealth.org",
    description:
      "Peach Tree Health provides primary care, dental, and behavioral health services to underserved communities in Yuba, Sutter, and surrounding rural Northern California counties.",
  },
  {
    name: "Open Door Community Health Centers",
    slug: "open-door-community-health-centers",
    city: "Arcata",
    county: "Humboldt",
    region: "Other",
    lat: 40.8665,
    lng: -124.0828,
    siteCount: 9,
    patientCount: "50,000+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.opendoorhealth.com",
    description:
      "Open Door Community Health Centers provides medical, dental, and behavioral health care to rural communities along the North Coast of California in Humboldt and Del Norte counties.",
  },
];
