// california-fqhcs.ts
// Comprehensive directory of California Federally Qualified Health Centers (FQHCs)

export interface CaliforniaFQHC {
  name: string;
  slug: string;
  city: string;
  county: string;
  region: "Los Angeles" | "San Diego" | "Bay Area" | "Sacramento" | "Central Valley" | "Inland Empire" | "Central Coast" | "North State" | "North Coast";
  lat: number;
  lng: number;
  siteCount: number;
  patientCount: string;
  staffCount: string;
  programs: string[];
  ehrSystem: string;
  website: string;
  description: string;
  glassdoorRating: number | null;
  glassdoorReviewCount: number | null;
  ecmProvider: boolean;
  nhscApproved: boolean;
  careersUrl: string | null;
  // Funding vulnerability data — percentage of patients at risk of losing Medi-Cal coverage due to policy changes
  servesUndocumented: boolean; // All FQHCs serve regardless of status (required by Section 330)
  coverageVulnerabilityPercent: number | null; // Estimated % of patients at risk of coverage loss (null = unknown)
  fundingImpactLevel: "high" | "moderate" | "low" | null; // Estimated revenue impact from coverage changes
  missionStatement: string | null; // Organization's mission statement
}

export const regions = [
  "Los Angeles",
  "San Diego",
  "Bay Area",
  "Sacramento",
  "Central Valley",
  "Inland Empire",
  "Central Coast",
  "North State",
  "North Coast",
] as const;

export const allPrograms = [
  "ECM",
  "CCM",
  "Community Supports",
  "BH Integration",
  "TCM",
  "BH-ASO",
] as const;

export const allEhrSystems = [
  "OCHIN Epic",
  "NextGen",
  "eClinicalWorks",
  "Cerner",
  "athenahealth",
  "Other",
] as const;

export const fqhcSalaryRanges = {
  "Community Health Worker": { min: 44000, max: 60000, avg: 52000 },
  "Care Coordinator": { min: 46000, max: 66000, avg: 56000 },
  "Medical Assistant": { min: 40000, max: 60000, avg: 49000 },
  "Case Manager": { min: 47000, max: 82000, avg: 68000 },
  "Licensed Clinical Social Worker": { min: 79000, max: 114000, avg: 93000 },
  "Registered Nurse": { min: 85000, max: 140000, avg: 110000 },
  "Nurse Practitioner": { min: 120000, max: 180000, avg: 145000 },
  "Dentist": { min: 150000, max: 220000, avg: 185000 },
  "Medical Director": { min: 250000, max: 400000, avg: 339000 },
  "Patient Services Coordinator": { min: 36000, max: 52000, avg: 41000 },
} as const;

export const typicalFqhcBenefits = [
  "NHSC Loan Repayment (up to $75,000 for 2-year commitment)",
  "Medical, Dental & Vision Insurance",
  "403(b) Retirement Plan",
  "Generous PTO (2-4 weeks + 13 paid holidays)",
  "Life & Disability Insurance",
  "Tuition Assistance / CME Support",
  "Employee Assistance Program (EAP)",
  "Malpractice Coverage (FTCA)",
  "340B Drug Pricing Discount",
  "Bilingual Pay Differential",
] as const;

export const californiaFQHCs: CaliforniaFQHC[] = [
  // ─────────────────────────────────────────────
  // LOS ANGELES REGION (23)
  // ─────────────────────────────────────────────
  {
    name: "AltaMed Health Services",
    slug: "altamed-health-services",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0244,
    lng: -118.1728,
    siteCount: 50,
    patientCount: "300,000+",
    staffCount: "1,500+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.altamed.org",
    description:
      "One of the largest FQHCs in the nation, AltaMed serves over 300,000 patients across Los Angeles and Orange counties with comprehensive primary care, dental, behavioral health, and senior services.",
    glassdoorRating: 3.3,
    glassdoorReviewCount: 391,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.careers.altamed.org/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "AltaMed provides comprehensive health services to all, regardless of ability to pay or immigration status, with a special commitment to Latino and multi-ethnic communities.",
  },
  {
    name: "APLA Health",
    slug: "apla-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0901,
    lng: -118.3617,
    siteCount: 8,
    patientCount: "15,000+",
    staffCount: "95+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://aplahealth.org",
    description:
      "APLA Health provides comprehensive medical, dental, behavioral health, and HIV specialty care with a focus on LGBTQ+ communities and underserved populations in Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://aplahealth.org/about/careers-and-internships-with-apla-health/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "APLA Health provides comprehensive medical, dental, behavioral health, and HIV specialty care with a focus on LGBTQ+ communities.",
  },
  {
    name: "ChapCare",
    slug: "chapcare",
    city: "Pasadena",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.1478,
    lng: -118.1445,
    siteCount: 6,
    patientCount: "30,000+",
    staffCount: "150+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.chapcare.org",
    description:
      "ChapCare is a nonprofit community health center providing primary care, dental, vision, and behavioral health services to families in the San Gabriel Valley and greater Pasadena area.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.chapcare.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "ChapCare provides comprehensive healthcare to families in the San Gabriel Valley and greater Pasadena area.",
  },
  {
    name: "Eisner Health",
    slug: "eisner-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0359,
    lng: -118.2595,
    siteCount: 7,
    patientCount: "50,000+",
    staffCount: "250+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.eisnerhealth.org",
    description:
      "Founded in 1920, Eisner Health offers comprehensive primary care, women's health, pediatrics, dental, and behavioral health services in downtown Los Angeles and surrounding communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.eisnerhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Eisner Health provides comprehensive, high-quality healthcare that is affordable and accessible to everyone.",
  },
  {
    name: "JWCH Institute",
    slug: "jwch-institute",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0453,
    lng: -118.2468,
    siteCount: 12,
    patientCount: "60,000+",
    staffCount: "300+",
    programs: ["ECM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.jwchinstitute.org",
    description:
      "JWCH Institute provides health care and related services for homeless and underserved individuals in Los Angeles County, including HIV/AIDS care, substance use treatment, and primary care.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.jwchinstitute.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "JWCH Institute provides healthcare and education to underserved populations, including homeless and near-homeless individuals.",
  },
  {
    name: "Los Angeles Christian Health Centers",
    slug: "los-angeles-christian-health-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0435,
    lng: -118.2453,
    siteCount: 4,
    patientCount: "12,000+",
    staffCount: "80+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.lachc.com",
    description:
      "Los Angeles Christian Health Centers offers compassionate, high-quality medical and dental care to those experiencing homelessness and poverty on Skid Row and surrounding neighborhoods.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.lachc.com/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "LACHC provides quality healthcare to uninsured, low-income residents of Los Angeles.",
  },
  {
    name: "Northeast Valley Health Corporation",
    slug: "northeast-valley-health-corporation",
    city: "San Fernando",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.2819,
    lng: -118.439,
    siteCount: 14,
    patientCount: "85,000+",
    staffCount: "450+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nevhc.org",
    description:
      "Northeast Valley Health Corporation operates 14 health centers across the San Fernando and Santa Clarita Valleys, providing primary care, dental, OB/GYN, and behavioral health services.",
    glassdoorRating: 3.2,
    glassdoorReviewCount: 46,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://nevhc.org/jobs/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Northeast Valley Health Corporation provides quality, comprehensive health care to all.",
  },
  {
    name: "South Central Family Health Center",
    slug: "south-central-family-health-center",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9925,
    lng: -118.2551,
    siteCount: 4,
    patientCount: "25,000+",
    staffCount: "120+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.scfhc.org",
    description:
      "South Central Family Health Center provides culturally competent medical, dental, and behavioral health services to predominantly Latino and African American communities in South Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://scfhc.org/join-our-team/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "South Central Family Health Center provides quality, affordable health care and support services to families in the South Los Angeles area.",
  },
  {
    name: "St. John's Community Health",
    slug: "st-johns-community-health",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0528,
    lng: -118.2442,
    siteCount: 18,
    patientCount: "100,000+",
    staffCount: "500+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.wellchild.org",
    description:
      "St. John's Community Health is one of the largest community health center networks in Los Angeles, providing comprehensive primary care, dental, and wellness services to underserved communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sjch.org/employment",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 40,
    fundingImpactLevel: "high",
    missionStatement: "St. John's is dedicated to improving the health of the under-served, particularly in the Santa Monica, Mar Vista, and South Los Angeles areas.",
  },
  {
    name: "T.H.E. Health and Wellness Centers",
    slug: "the-health-and-wellness-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9831,
    lng: -118.3064,
    siteCount: 5,
    patientCount: "20,000+",
    staffCount: "110+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.thehealthandwellness.org",
    description:
      "T.H.E. Health and Wellness Centers is a women-founded organization providing comprehensive health services to underserved communities in South Los Angeles, with a focus on women and children.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.thehealthandwellness.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "T.H.E. Health and Wellness Centers provides holistic health care to underserved communities in South Los Angeles.",
  },
  {
    name: "Venice Family Clinic",
    slug: "venice-family-clinic",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9962,
    lng: -118.4628,
    siteCount: 14,
    patientCount: "45,000+",
    staffCount: "250+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://venicefamilyclinic.org",
    description:
      "Venice Family Clinic is the largest free clinic in the nation, providing quality primary care, dental, mental health, and specialty services to people in need across the Westside and South Bay.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://venicefamilyclinic.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Venice Family Clinic provides quality primary healthcare to people in need.",
  },
  {
    name: "Watts Healthcare Corporation",
    slug: "watts-healthcare-corporation",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9425,
    lng: -118.2451,
    siteCount: 3,
    patientCount: "18,000+",
    staffCount: "90+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.wattshealth.org",
    description:
      "Watts Healthcare Corporation has served the Watts community since 1967, providing primary care, dental, behavioral health, and HIV services to one of Los Angeles County's most underserved areas.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.wattshealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Watts Healthcare Corporation provides quality healthcare to the residents of Watts and surrounding communities.",
  },
  {
    name: "Herald Christian Health Center",
    slug: "herald-christian-health-center",
    city: "Rosemead",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0806,
    lng: -118.073,
    siteCount: 3,
    patientCount: "22,000+",
    staffCount: "110+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.heraldhealth.org",
    description:
      "Herald Christian Health Center provides culturally and linguistically appropriate medical, dental, and behavioral health services to Asian and Pacific Islander communities in the San Gabriel Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.heraldhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "Herald Christian Health Center provides quality healthcare to all, regardless of ability to pay, particularly serving Asian and Pacific Islander communities.",
  },
  {
    name: "Community Health Alliance of Pasadena",
    slug: "community-health-alliance-of-pasadena",
    city: "Pasadena",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.1473,
    lng: -118.1312,
    siteCount: 5,
    patientCount: "20,000+",
    staffCount: "110+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.chaphealth.org",
    description:
      "Community Health Alliance of Pasadena (CHAP) delivers high-quality primary care, behavioral health, and dental services to the diverse communities of Pasadena and surrounding areas.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.chaphealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "CHAP is dedicated to providing quality healthcare to all, regardless of ability to pay.",
  },
  {
    name: "UMMA Community Clinic",
    slug: "umma-community-clinic",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9878,
    lng: -118.2999,
    siteCount: 2,
    patientCount: "10,000+",
    staffCount: "60+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.ummaclinic.org",
    description:
      "UMMA Community Clinic provides high-quality health care to South Los Angeles, promoting a health model that combines medicine with neighborhood-level community development and wellness.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.ummaclinic.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 45,
    fundingImpactLevel: "high",
    missionStatement: "UMMA Community Clinic provides high-quality healthcare for all, regardless of ability to pay, in the spirit of giving.",
  },
  {
    name: "Comprehensive Community Health Centers",
    slug: "comprehensive-community-health-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0356,
    lng: -118.2468,
    siteCount: 6,
    patientCount: "35,000+",
    staffCount: "175+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.cchs-la.org",
    description:
      "Comprehensive Community Health Centers provides integrated medical, dental, and behavioral health services to low-income and uninsured populations throughout Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.cchs-la.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Comprehensive Community Health Centers provides quality primary healthcare and social services to the underserved in the South Los Angeles community.",
  },
  {
    name: "Central Neighborhood Health Foundation",
    slug: "central-neighborhood-health-foundation",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0298,
    lng: -118.2512,
    siteCount: 4,
    patientCount: "16,000+",
    staffCount: "85+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.cnhf-la.org",
    description:
      "Central Neighborhood Health Foundation serves downtown Los Angeles with culturally competent primary care, dental, and mental health services to homeless and unstably housed populations.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.cnhf-la.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "CNHF promotes better health outcomes for the uninsured and underserved communities in South Los Angeles.",
  },
  {
    name: "Kheir Clinic",
    slug: "kheir-clinic",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9950,
    lng: -118.2750,
    siteCount: 3,
    patientCount: "12,000+",
    staffCount: "70+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.kheirclinic.org",
    description:
      "Kheir Clinic provides affordable medical and dental care with cultural competence to Middle Eastern and other immigrant communities in South Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.kheirclinic.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 40,
    fundingImpactLevel: "high",
    missionStatement: "Kheir Clinic delivers culturally sensitive healthcare and community services to underserved populations in the greater Los Angeles area.",
  },
  {
    name: "South Bay Family Health Care",
    slug: "south-bay-family-health-care",
    city: "Harbor City",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.7425,
    lng: -118.3265,
    siteCount: 5,
    patientCount: "24,000+",
    staffCount: "130+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.sbfhc.org",
    description:
      "South Bay Family Health Care provides primary care, dental, behavioral health, and specialty services to underserved families in the Los Angeles South Bay area.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sbfhc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "South Bay Family Health Care provides quality healthcare to the communities of the South Bay.",
  },
  {
    name: "QueensCare Health Centers",
    slug: "queenscare-health-centers",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0512,
    lng: -118.2385,
    siteCount: 7,
    patientCount: "42,000+",
    staffCount: "220+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.queenscare.org",
    description:
      "QueensCare Health Centers serves low-income families and individuals with comprehensive primary care, dental, vision, behavioral health, and specialty care services throughout Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.queenscare.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "QueensCare Health Centers provides quality healthcare and social services to underserved communities in Greater Los Angeles.",
  },
  {
    name: "Kedren Community Health Center",
    slug: "kedren-community-health-center",
    city: "Los Angeles",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 33.9678,
    lng: -118.2421,
    siteCount: 4,
    patientCount: "18,000+",
    staffCount: "100+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.kedren.org",
    description:
      "Kedren Community Health Center provides primary care, dental, and comprehensive behavioral health services with a focus on substance abuse treatment and recovery in South Los Angeles.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.kedren.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Kedren Community Health Center provides quality health and human services to underserved communities in South Los Angeles.",
  },
  {
    name: "Westside Family Health Center",
    slug: "westside-family-health-center",
    city: "Santa Monica",
    county: "Los Angeles",
    region: "Los Angeles",
    lat: 34.0195,
    lng: -118.4812,
    siteCount: 3,
    patientCount: "14,000+",
    staffCount: "75+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.wfhc-la.org",
    description:
      "Westside Family Health Center provides accessible primary care, dental, and mental health services to low-income families and individuals on Los Angeles' Westside.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.wfhc-la.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Westside Family Health Center provides accessible, quality healthcare to all, regardless of ability to pay.",
  },

  // ─────────────────────────────────────────────
  // SAN DIEGO REGION (10)
  // ─────────────────────────────────────────────
  {
    name: "Family Health Centers of San Diego",
    slug: "family-health-centers-of-san-diego",
    city: "San Diego",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7157,
    lng: -117.1611,
    siteCount: 47,
    patientCount: "227,000+",
    staffCount: "1,200+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.fhcsd.org",
    description:
      "Family Health Centers of San Diego is the region's largest FQHC, providing medical, dental, behavioral health, HIV services, and housing support across 47 sites throughout San Diego County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.fhcsd.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 25,
    fundingImpactLevel: "high",
    missionStatement: "Family Health Centers of San Diego provides caring, affordable, high-quality healthcare and supportive services to everyone, with a special commitment to uninsured, low-income, and medically underserved persons.",
  },
  {
    name: "La Maestra Community Health Centers",
    slug: "la-maestra-community-health-centers",
    city: "San Diego",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7716,
    lng: -117.0643,
    siteCount: 10,
    patientCount: "80,000+",
    staffCount: "420+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.lamaestra.org",
    description:
      "La Maestra Community Health Centers serves the refugee and immigrant communities of City Heights and surrounding San Diego neighborhoods with culturally competent comprehensive health care.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.lamaestra.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 40,
    fundingImpactLevel: "high",
    missionStatement: "La Maestra provides accessible and affordable quality health and human services to culturally diverse communities in the San Diego area.",
  },
  {
    name: "San Ysidro Health",
    slug: "san-ysidro-health",
    city: "San Ysidro",
    county: "San Diego",
    region: "San Diego",
    lat: 32.5556,
    lng: -117.0462,
    siteCount: 35,
    patientCount: "113,000+",
    staffCount: "580+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.syhealth.org",
    description:
      "San Ysidro Health is one of the largest FQHCs in the nation, providing medical, dental, behavioral health, chiropractic, and optometry services to communities along the U.S.-Mexico border.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.syhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 45,
    fundingImpactLevel: "high",
    missionStatement: "San Ysidro Health is committed to providing quality, compassionate healthcare to all in need, regardless of circumstance, in the border region.",
  },
  {
    name: "Neighborhood Healthcare",
    slug: "neighborhood-healthcare",
    city: "Escondido",
    county: "San Diego",
    region: "San Diego",
    lat: 33.1192,
    lng: -117.0864,
    siteCount: 19,
    patientCount: "90,000+",
    staffCount: "480+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nhcare.org",
    description:
      "Neighborhood Healthcare provides comprehensive medical, dental, behavioral health, and specialty care at 19 sites across San Diego and Riverside counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.nhcare.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Neighborhood Healthcare provides quality, comprehensive healthcare to everyone.",
  },
  {
    name: "Vista Community Clinic",
    slug: "vista-community-clinic",
    city: "Vista",
    county: "San Diego",
    region: "San Diego",
    lat: 33.2003,
    lng: -117.2425,
    siteCount: 8,
    patientCount: "65,000+",
    staffCount: "340+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.vistacommunityclinic.org",
    description:
      "Vista Community Clinic provides affordable primary care, pediatrics, prenatal, dental, and behavioral health services to North San Diego County communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.vistacommunityclinic.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Vista Community Clinic provides quality healthcare to the communities of North County San Diego.",
  },
  {
    name: "Mountain Health and Community Services",
    slug: "mountain-health-and-community-services",
    city: "Lake Cuyamaca",
    county: "San Diego",
    region: "San Diego",
    lat: 32.9888,
    lng: -116.5739,
    siteCount: 3,
    patientCount: "8,000+",
    staffCount: "50+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "athenahealth",
    website: "https://www.mtnhealth.org",
    description:
      "Mountain Health and Community Services provides primary care and community services to rural and frontier communities in the mountain regions of eastern San Diego County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.mtnhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Mountain Health provides comprehensive healthcare and community services to the rural communities of San Diego's backcountry.",
  },
  {
    name: "Borrego Health - San Diego",
    slug: "borrego-health-san-diego",
    city: "El Cajon",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7948,
    lng: -116.9625,
    siteCount: 6,
    patientCount: "35,000+",
    staffCount: "180+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.borregohealth.org",
    description:
      "Borrego Health's San Diego sites provide comprehensive medical, dental, and behavioral health care to diverse communities across East County San Diego.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.borregohealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Borrego Health provides quality healthcare to all, regardless of their ability to pay or immigration status.",
  },
  {
    name: "Imperial Beach Health Center",
    slug: "imperial-beach-health-center",
    city: "Imperial Beach",
    county: "San Diego",
    region: "San Diego",
    lat: 32.584,
    lng: -117.1131,
    siteCount: 2,
    patientCount: "12,000+",
    staffCount: "65+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.ibhealthcenter.org",
    description:
      "Imperial Beach Health Center delivers primary care, prenatal, and pediatric services to the southernmost coastal community in San Diego County near the U.S.-Mexico border.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.ibhealthcenter.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Imperial Beach Health Center provides quality healthcare to the Imperial Beach community.",
  },
  {
    name: "TrueCare",
    slug: "truecare",
    city: "Oceanside",
    county: "San Diego",
    region: "San Diego",
    lat: 33.1959,
    lng: -117.3795,
    siteCount: 12,
    patientCount: "75,000+",
    staffCount: "400+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.truecare.org",
    description:
      "TrueCare (formerly North County Health Services) provides comprehensive primary care, dental, behavioral health, and specialty services to North County San Diego communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.truecare.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "TrueCare provides quality, compassionate healthcare to all community members.",
  },
  {
    name: "Planned Parenthood of the Pacific Southwest",
    slug: "planned-parenthood-pacific-southwest",
    city: "San Diego",
    county: "San Diego",
    region: "San Diego",
    lat: 32.7158,
    lng: -117.1610,
    siteCount: 5,
    patientCount: "28,000+",
    staffCount: "150+",
    programs: ["BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.plannedparenthood.org",
    description:
      "Planned Parenthood of the Pacific Southwest provides comprehensive reproductive health care, family planning, and preventive services across San Diego, Riverside, and Santa Cruz counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: false,
    nhscApproved: true,
    careersUrl: "https://www.plannedparenthood.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Planned Parenthood of the Pacific Southwest provides expert healthcare and education.",
  },

  // ─────────────────────────────────────────────
  // BAY AREA REGION (19)
  // ─────────────────────────────────────────────
  {
    name: "Mission Neighborhood Health Center",
    slug: "mission-neighborhood-health-center",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7599,
    lng: -122.4148,
    siteCount: 3,
    patientCount: "12,000+",
    staffCount: "150+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.mnhc.org",
    description:
      "Founded in 1967, Mission Neighborhood Health Center serves San Francisco's Mission District with culturally competent, bilingual primary care, behavioral health, HIV services, and chronic disease management for immigrant and Latino communities.",
    glassdoorRating: 3.1,
    glassdoorReviewCount: 32,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.mnhc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Mission Neighborhood Health Center provides quality healthcare and support services to the diverse communities of the Mission District.",
  },
  {
    name: "LifeLong Medical Care",
    slug: "lifelong-medical-care",
    city: "Berkeley",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8702,
    lng: -122.2728,
    siteCount: 15,
    patientCount: "66,000+",
    staffCount: "350+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.lifelongmedical.org",
    description:
      "LifeLong Medical Care provides comprehensive health and social services to underserved people of all ages throughout the East Bay, including medical, dental, behavioral health, and homeless services.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://lifelongmedical.org/job-opportunities/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "LifeLong Medical Care provides quality healthcare and support services to underserved communities in the East Bay.",
  },
  {
    name: "Asian Health Services",
    slug: "asian-health-services",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.7985,
    lng: -122.2711,
    siteCount: 5,
    patientCount: "50,000+",
    staffCount: "265+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.asianhealthservices.org",
    description:
      "Asian Health Services provides medical, dental, behavioral health, and enabling services in over 14 languages to the diverse Asian communities in Oakland's Chinatown and beyond.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://jobs.lever.co/ahschc",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Asian Health Services provides health, social, and advocacy services to the medically underserved in Alameda County.",
  },
  {
    name: "La Clinica de La Raza",
    slug: "la-clinica-de-la-raza",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.7807,
    lng: -122.2228,
    siteCount: 35,
    patientCount: "90,000+",
    staffCount: "475+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.laclinica.org",
    description:
      "La Clinica de La Raza is a leading community health center network offering culturally appropriate medical, dental, behavioral health, and optometry services across the East Bay and Contra Costa County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://laclinica.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "La Clínica provides culturally appropriate, quality, and accessible health care to the diverse communities of the San Francisco Bay Area.",
  },
  {
    name: "North East Medical Services",
    slug: "north-east-medical-services",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7941,
    lng: -122.4078,
    siteCount: 9,
    patientCount: "45,000+",
    staffCount: "240+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.nems.org",
    description:
      "North East Medical Services is a nonprofit community health center providing multilingual primary care, dental, behavioral health, and specialty services to Asian American communities in San Francisco.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.nems.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "North East Medical Services provides quality healthcare to medically underserved communities in the San Francisco Bay Area.",
  },
  {
    name: "Ravenswood Family Health Network",
    slug: "ravenswood-family-health-network",
    city: "East Palo Alto",
    county: "San Mateo",
    region: "Bay Area",
    lat: 37.4688,
    lng: -122.1411,
    siteCount: 5,
    patientCount: "20,000+",
    staffCount: "110+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.ravenswoodfhn.org",
    description:
      "Ravenswood Family Health Network provides comprehensive primary care, dental, and behavioral health services to underserved communities on the San Francisco Peninsula, including East Palo Alto and Belle Haven.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://ravenswoodfhn.org/get-involved/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Ravenswood Family Health Network provides healthcare services to the diverse communities of the mid-Peninsula.",
  },
  {
    name: "Gardner Health Services",
    slug: "gardner-health-services",
    city: "San Jose",
    county: "Santa Clara",
    region: "Bay Area",
    lat: 37.3293,
    lng: -121.8894,
    siteCount: 9,
    patientCount: "42,000+",
    staffCount: "220+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.gardnerhealthservices.org",
    description:
      "Gardner Health Services provides culturally sensitive primary care, dental, behavioral health, and specialty care to diverse communities in Santa Clara County, including migrant and seasonal farmworkers.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.gardnerhealthservices.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Gardner Health Services provides comprehensive healthcare to the diverse communities of Santa Clara County.",
  },
  {
    name: "San Francisco Community Health Center",
    slug: "san-francisco-community-health-center",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7849,
    lng: -122.4094,
    siteCount: 5,
    patientCount: "15,000+",
    staffCount: "85+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.sfcommunityhealth.org",
    description:
      "San Francisco Community Health Center provides culturally competent primary care, behavioral health, and transgender health services with a focus on Asian and Pacific Islander and LGBTQ+ communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sfcommunityhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "San Francisco Community Health Center provides quality, compassionate care to the diverse communities of San Francisco.",
  },
  {
    name: "Native American Health Center",
    slug: "native-american-health-center",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8044,
    lng: -122.2712,
    siteCount: 4,
    patientCount: "14,000+",
    staffCount: "75+",
    programs: ["ECM", "BH Integration", "Community Supports", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.nativehealth.org",
    description:
      "Native American Health Center provides comprehensive medical, dental, behavioral health, and traditional healing services to Native American and underserved communities in Oakland and San Francisco.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.nativehealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Native American Health Center provides comprehensive healthcare to the Native American community and all people.",
  },
  {
    name: "Tiburcio Vasquez Health Center",
    slug: "tiburcio-vasquez-health-center",
    city: "Hayward",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.6688,
    lng: -122.0808,
    siteCount: 8,
    patientCount: "35,000+",
    staffCount: "185+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.tvhc.org",
    description:
      "Tiburcio Vasquez Health Center offers primary care, dental, optometry, behavioral health, and women's health services to underserved communities across southern Alameda County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.tvhc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "Tiburcio Vasquez Health Center provides quality healthcare and community services in southern Alameda County.",
  },
  {
    name: "Axis Community Health",
    slug: "axis-community-health",
    city: "Pleasanton",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.6624,
    lng: -121.8747,
    siteCount: 4,
    patientCount: "16,000+",
    staffCount: "90+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.axishealth.org",
    description:
      "Axis Community Health provides primary medical care, behavioral health, and substance use treatment to families in the Tri-Valley area of eastern Alameda County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.axishealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Axis Community Health provides quality healthcare services to all community members in the Tri-Valley.",
  },
  {
    name: "Bay Area Community Health (BACH)",
    slug: "bay-area-community-health",
    city: "Union City",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.5917,
    lng: -122.0748,
    siteCount: 8,
    patientCount: "67,000+",
    staffCount: "558+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.bach-health.org",
    description:
      "Bay Area Community Health operates comprehensive health centers across the East Bay with integrated primary care, dental, behavioral health, and community support services.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.bach-health.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Bay Area Community Health provides quality healthcare to the communities of the Tri-City area.",
  },
  {
    name: "Marin Community Clinics",
    slug: "marin-community-clinics",
    city: "San Rafael",
    county: "Marin",
    region: "Bay Area",
    lat: 37.9738,
    lng: -122.5254,
    siteCount: 6,
    patientCount: "32,000+",
    staffCount: "170+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.marinclinics.org",
    description:
      "Marin Community Clinics provides primary care, dental, behavioral health, and preventive services to low-income and underserved individuals and families throughout Marin County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.marinclinics.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Marin Community Clinics provides quality healthcare to all Marin County residents, regardless of ability to pay.",
  },
  {
    name: "West Oakland Health Council",
    slug: "west-oakland-health-council",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8219,
    lng: -122.3006,
    siteCount: 4,
    patientCount: "18,000+",
    staffCount: "100+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.wohc.org",
    description:
      "West Oakland Health Council provides culturally responsive primary care, dental, behavioral health, and community services to West Oakland's African American and immigrant communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.wohc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "West Oakland Health Council provides quality healthcare to the communities of West Oakland.",
  },
  {
    name: "Tri-City Health Center",
    slug: "tri-city-health-center",
    city: "Fremont",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.5485,
    lng: -121.9886,
    siteCount: 5,
    patientCount: "28,000+",
    staffCount: "150+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.tricityhealth.org",
    description:
      "Tri-City Health Center serves Fremont, Newark, and Union City with comprehensive primary care, dental, and behavioral health services to diverse populations.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.tricityhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Tri-City Health Center provides quality healthcare to the communities of the southern Alameda County.",
  },
  {
    name: "HealthRIGHT 360",
    slug: "healthright-360",
    city: "San Francisco",
    county: "San Francisco",
    region: "Bay Area",
    lat: 37.7749,
    lng: -122.4194,
    siteCount: 11,
    patientCount: "52,000+",
    staffCount: "280+",
    programs: ["ECM", "BH Integration", "Community Supports", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.healthright360.org",
    description:
      "HealthRIGHT 360 provides integrated behavioral health and primary care services to vulnerable populations including those experiencing homelessness and living with HIV in San Francisco and statewide.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.healthright360.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "HealthRIGHT 360 provides integrated healthcare and social services to people in need.",
  },
  {
    name: "Planned Parenthood Mar Monte",
    slug: "planned-parenthood-mar-monte",
    city: "San Jose",
    county: "Santa Clara",
    region: "Bay Area",
    lat: 37.3382,
    lng: -121.8863,
    siteCount: 7,
    patientCount: "38,000+",
    staffCount: "200+",
    programs: ["BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.ppmarmonte.org",
    description:
      "Planned Parenthood Mar Monte provides comprehensive reproductive health care, family planning, primary care, and preventive services across Central California.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: false,
    nhscApproved: true,
    careersUrl: "https://www.ppmarmonte.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Planned Parenthood Mar Monte provides healthcare and education to communities across Northern and Central California.",
  },
  {
    name: "Sausal Creek Health Center",
    slug: "sausal-creek-health-center",
    city: "Oakland",
    county: "Alameda",
    region: "Bay Area",
    lat: 37.8175,
    lng: -122.2489,
    siteCount: 3,
    patientCount: "14,000+",
    staffCount: "75+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.sausalcreekhealth.org",
    description:
      "Sausal Creek Health Center provides primary care and behavioral health services to underserved communities in Oakland's Fruitvale district.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sausalcreekhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Sausal Creek Health Center provides quality healthcare to the diverse communities of the Oakland Hills.",
  },
  {
    name: "Salud Para La Gente",
    slug: "salud-para-la-gente",
    city: "Watsonville",
    county: "Santa Cruz",
    region: "Bay Area",
    lat: 36.9102,
    lng: -121.7605,
    siteCount: 5,
    patientCount: "26,000+",
    staffCount: "140+",
    programs: ["ECM", "CCM", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.saludparalaagente.org",
    description:
      "Salud Para La Gente provides comprehensive primary care, dental, behavioral health, and agricultural worker health services to rural communities in Santa Cruz and Monterey counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.saludparalaagente.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "Salud Para La Gente provides quality, comprehensive healthcare to uninsured and underserved communities in Santa Cruz County.",
  },

  // ─────────────────────────────────────────────
  // SACRAMENTO REGION (7)
  // ─────────────────────────────────────────────
  {
    name: "WellSpace Health",
    slug: "wellspace-health",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5816,
    lng: -121.4944,
    siteCount: 17,
    patientCount: "70,000+",
    staffCount: "375+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.wellspacehealth.org",
    description:
      "WellSpace Health is the Sacramento region's largest FQHC, providing primary care, dental, behavioral health, addiction medicine, and crisis services across 17 locations.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.wellspacehealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "WellSpace Health provides quality, integrated healthcare to all community members in the Sacramento region.",
  },
  {
    name: "Sacramento Native American Health Center",
    slug: "sacramento-native-american-health-center",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5649,
    lng: -121.4687,
    siteCount: 3,
    patientCount: "12,000+",
    staffCount: "70+",
    programs: ["ECM", "BH Integration", "Community Supports", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.snahc.org",
    description:
      "Sacramento Native American Health Center provides culturally responsive medical, dental, behavioral health, and traditional healing services to Native American and other underserved communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.snahc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Sacramento Native American Health Center provides quality healthcare to the Native American community and all underserved populations.",
  },
  {
    name: "Elica Health Centers",
    slug: "elica-health-centers",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5961,
    lng: -121.4404,
    siteCount: 7,
    patientCount: "45,000+",
    staffCount: "240+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.elicahealth.org",
    description:
      "Elica Health Centers provides primary care, dental, behavioral health, and pharmacy services to Sacramento's diverse refugee and immigrant communities in over 40 languages.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.elicahealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Elica Health Centers provides quality healthcare services to all, with a special commitment to diverse communities.",
  },
  {
    name: "CommuniCare Health Centers",
    slug: "communicare-health-centers",
    city: "Davis",
    county: "Yolo",
    region: "Sacramento",
    lat: 38.5449,
    lng: -121.7405,
    siteCount: 8,
    patientCount: "38,000+",
    staffCount: "200+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.communicarehc.org",
    description:
      "CommuniCare Health Centers provides comprehensive medical, dental, and behavioral health services to underserved communities across Yolo County, including Davis, Woodland, and West Sacramento.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://communicareole.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "CommuniCare Health Centers provides quality, affordable healthcare to the communities of Yolo County.",
  },
  {
    name: "One Community Health",
    slug: "one-community-health",
    city: "Sacramento",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.5752,
    lng: -121.4689,
    siteCount: 5,
    patientCount: "25,000+",
    staffCount: "135+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.onecommunityhealth.com",
    description:
      "One Community Health provides affirming primary care, sexual health, behavioral health, and pharmacy services with a focus on LGBTQ+ communities and people living with HIV in the Sacramento area.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.onecommunityhealth.com/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "One Community Health provides quality, integrated healthcare to all in the Sacramento region.",
  },
  {
    name: "Sierra Vista Community Health",
    slug: "sierra-vista-community-health-sacramento",
    city: "Citrus Heights",
    county: "Sacramento",
    region: "Sacramento",
    lat: 38.6382,
    lng: -121.2608,
    siteCount: 4,
    patientCount: "20,000+",
    staffCount: "110+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.sierravistahc.org",
    description:
      "Sierra Vista Community Health provides primary care, dental, behavioral health, and preventive services to underserved communities in the Sacramento metropolitan area.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sierravistahc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Sierra Vista Community Health provides quality healthcare to the communities of Sacramento.",
  },
  {
    name: "Ampla Health - Sacramento",
    slug: "ampla-health-sacramento",
    city: "Yuba City",
    county: "Sutter",
    region: "Sacramento",
    lat: 38.9272,
    lng: -121.6100,
    siteCount: 9,
    patientCount: "48,000+",
    staffCount: "250+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.amplahealth.org",
    description:
      "Ampla Health operates comprehensive health centers across northern California with primary care, dental, behavioral health, and specialty services to rural and agricultural communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.amplahealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Ampla Health provides quality healthcare to the communities of Northern California.",
  },

  // ─────────────────────────────────────────────
  // CENTRAL VALLEY REGION (10)
  // ─────────────────────────────────────────────
  {
    name: "Clinica Sierra Vista",
    slug: "clinica-sierra-vista",
    city: "Bakersfield",
    county: "Kern",
    region: "Central Valley",
    lat: 35.3733,
    lng: -119.0187,
    siteCount: 38,
    patientCount: "200,000+",
    staffCount: "1,050+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.clinicasierravista.org",
    description:
      "Clinica Sierra Vista is the largest FQHC in Kern County and one of the largest in California, operating 38 sites providing medical, dental, behavioral health, and WIC services.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.clinicasierravista.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Clinica Sierra Vista provides accessible, quality healthcare with compassion and respect to all.",
  },
  {
    name: "United Health Centers",
    slug: "united-health-centers",
    city: "Parlier",
    county: "Fresno",
    region: "Central Valley",
    lat: 36.6117,
    lng: -119.5271,
    siteCount: 22,
    patientCount: "120,000+",
    staffCount: "630+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.unitedhealthcenters.org",
    description:
      "United Health Centers provides comprehensive medical, dental, optometry, and behavioral health care to agricultural communities across Fresno, Kings, and Tulare counties in the San Joaquin Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.unitedhealthcenters.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "United Health Centers provides quality health care services to our communities regardless of ability to pay.",
  },
  {
    name: "Family HealthCare Network",
    slug: "family-healthcare-network",
    city: "Visalia",
    county: "Tulare",
    region: "Central Valley",
    lat: 36.3302,
    lng: -119.2921,
    siteCount: 45,
    patientCount: "175,000+",
    staffCount: "920+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.fhcn.org",
    description:
      "Family HealthCare Network operates 45 sites across Tulare and Kings counties, providing primary care, dental, behavioral health, and pharmacy services primarily to farmworker families.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.fhcn.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 25,
    fundingImpactLevel: "high",
    missionStatement: "Family HealthCare Network provides quality health care to all community members regardless of barriers.",
  },
  {
    name: "Camarena Health",
    slug: "camarena-health",
    city: "Madera",
    county: "Madera",
    region: "Central Valley",
    lat: 36.9613,
    lng: -120.0607,
    siteCount: 7,
    patientCount: "45,000+",
    staffCount: "240+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.camarenahealth.org",
    description:
      "Camarena Health provides primary care, dental, optometry, and behavioral health services to the agricultural communities of Madera County in California's Central Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.camarenahealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Camarena Health is dedicated to providing accessible, quality healthcare to the communities of Madera County.",
  },
  {
    name: "Golden Valley Health Centers",
    slug: "golden-valley-health-centers",
    city: "Merced",
    county: "Merced",
    region: "Central Valley",
    lat: 37.3022,
    lng: -120.483,
    siteCount: 14,
    patientCount: "75,000+",
    staffCount: "395+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.gvhc.org",
    description:
      "Golden Valley Health Centers serves Merced and Stanislaus counties with comprehensive medical, dental, behavioral health, and pediatric specialty services in California's Central Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.gvhc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Golden Valley Health Centers provides quality, affordable healthcare to underserved communities in the Central Valley.",
  },
  {
    name: "Omni Family Health",
    slug: "omni-family-health",
    city: "Bakersfield",
    county: "Kern",
    region: "Central Valley",
    lat: 35.3732,
    lng: -119.0188,
    siteCount: 26,
    patientCount: "100,000+",
    staffCount: "520+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.omnifamilyhealth.org",
    description:
      "Omni Family Health operates 26 health centers across Kern, Los Angeles, and San Bernardino counties, providing medical, dental, and behavioral health services to underserved communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.omnifamilyhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 25,
    fundingImpactLevel: "high",
    missionStatement: "Omni Family Health provides quality health care and support services to the communities we serve.",
  },
  {
    name: "Livingston Community Health",
    slug: "livingston-community-health",
    city: "Livingston",
    county: "Merced",
    region: "Central Valley",
    lat: 37.3866,
    lng: -120.7231,
    siteCount: 4,
    patientCount: "18,000+",
    staffCount: "95+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.livingstoncommhealth.org",
    description:
      "Livingston Community Health provides primary care, dental, and behavioral health services to the rural agricultural communities of the northern San Joaquin Valley in Merced County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.livingstoncommhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "Livingston Community Health provides high-quality health services to underserved communities in Merced County.",
  },
  {
    name: "Adventist Health - Central Valley",
    slug: "adventist-health-central-valley",
    city: "Turlock",
    county: "Stanislaus",
    region: "Central Valley",
    lat: 37.4847,
    lng: -120.8604,
    siteCount: 6,
    patientCount: "34,000+",
    staffCount: "180+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "Cerner",
    website: "https://www.adventisthealth.org",
    description:
      "Adventist Health operates community clinics throughout the Central Valley providing primary care, preventive services, and behavioral health care to underserved populations.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.adventisthealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Adventist Health provides quality, compassionate healthcare to communities in the Central Valley.",
  },
  {
    name: "Salud Para La Gente - Central Valley",
    slug: "salud-para-la-gente-central-valley",
    city: "Delano",
    county: "Kern",
    region: "Central Valley",
    lat: 35.7680,
    lng: -119.2425,
    siteCount: 8,
    patientCount: "42,000+",
    staffCount: "220+",
    programs: ["ECM", "CCM", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.saludparalaagente.org",
    description:
      "Salud Para La Gente Central Valley operations provide comprehensive primary care, dental, behavioral health, and agricultural worker health services to Kern County communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.saludparalaagente.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "Salud Para La Gente provides quality, comprehensive healthcare to uninsured and underserved communities.",
  },

  // ─────────────────────────────────────────────
  // INLAND EMPIRE REGION (9)
  // ─────────────────────────────────────────────
  {
    name: "Borrego Health",
    slug: "borrego-health",
    city: "Brawley",
    county: "Imperial",
    region: "Inland Empire",
    lat: 32.9787,
    lng: -115.5303,
    siteCount: 28,
    patientCount: "150,000+",
    staffCount: "785+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "NextGen",
    website: "https://www.borregohealth.org",
    description:
      "Borrego Health is one of the largest FQHCs in California, providing medical, dental, and behavioral health services across Imperial, Riverside, and San Bernardino counties and the Coachella Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.borregohealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Borrego Health provides quality healthcare to all, regardless of their ability to pay or immigration status.",
  },
  {
    name: "SAC Health",
    slug: "sac-health",
    city: "San Bernardino",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.1083,
    lng: -117.2898,
    siteCount: 10,
    patientCount: "60,000+",
    staffCount: "315+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.sachealthsystem.org",
    description:
      "SAC Health provides comprehensive primary care, dental, behavioral health, and pediatric specialty services to underserved communities throughout San Bernardino County's Inland Empire.",
    glassdoorRating: 2.8,
    glassdoorReviewCount: 20,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sachealthsystem.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 20,
    fundingImpactLevel: "moderate",
    missionStatement: "SAC Health provides compassionate, quality healthcare to all, regardless of ability to pay.",
  },
  {
    name: "Desert Healthcare District & Foundation",
    slug: "desert-healthcare-district",
    city: "Palm Springs",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.8303,
    lng: -116.5453,
    siteCount: 4,
    patientCount: "25,000+",
    staffCount: "135+",
    programs: ["ECM", "Community Supports", "BH Integration"],
    ehrSystem: "athenahealth",
    website: "https://www.dhcd.org",
    description:
      "Desert Healthcare District supports access to health and wellness services in the eastern Coachella Valley, funding community health programs and providing primary care in the desert region.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.dhcd.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Desert Healthcare District promotes healthy communities in the Coachella Valley.",
  },
  {
    name: "Riverside University Health System - Community Health Centers",
    slug: "riverside-university-health-system-chc",
    city: "Riverside",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.9533,
    lng: -117.3962,
    siteCount: 12,
    patientCount: "80,000+",
    staffCount: "420+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration", "TCM"],
    ehrSystem: "Cerner",
    website: "https://www.ruhealth.org",
    description:
      "Riverside University Health System's Community Health Centers provide medical, dental, behavioral health, and public health services at 12 locations throughout Riverside County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.ruhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Riverside University Health System provides quality healthcare to all Riverside County residents.",
  },
  {
    name: "Loma Linda University Health - SAC Health",
    slug: "loma-linda-university-health-sac",
    city: "Loma Linda",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.0483,
    lng: -117.2613,
    siteCount: 6,
    patientCount: "35,000+",
    staffCount: "185+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "Cerner",
    website: "https://www.lluh.org",
    description:
      "Loma Linda University Health's community health programs provide primary care, preventive services, and specialty care access to underserved populations in the Inland Empire.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.lluh.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Loma Linda University Health provides quality, faith-based healthcare to all communities.",
  },
  {
    name: "Community Health Systems, Inc.",
    slug: "community-health-systems-inc",
    city: "Riverside",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.9805,
    lng: -117.3755,
    siteCount: 9,
    patientCount: "55,000+",
    staffCount: "290+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.chsica.org",
    description:
      "Community Health Systems provides medical, dental, and behavioral health services at multiple sites in Riverside and San Bernardino counties, serving diverse Inland Empire communities.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.chsica.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Community Health Systems provides quality healthcare services to the community.",
  },
  {
    name: "Inland Faculty Medical Group",
    slug: "inland-faculty-medical-group",
    city: "Colton",
    county: "San Bernardino",
    region: "Inland Empire",
    lat: 34.0739,
    lng: -117.3137,
    siteCount: 5,
    patientCount: "30,000+",
    staffCount: "160+",
    programs: ["ECM", "BH Integration", "CCM"],
    ehrSystem: "Cerner",
    website: "https://www.arrowheadmedcenter.org",
    description:
      "Inland Faculty Medical Group operates community health sites affiliated with Arrowhead Regional Medical Center, providing primary care and specialty services in San Bernardino County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.arrowheadmedcenter.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "Inland Faculty Medical Group provides quality healthcare services to the Inland Empire.",
  },
  {
    name: "Clinicas de Salud del Pueblo",
    slug: "clinicas-de-salud-del-pueblo",
    city: "Brawley",
    county: "Imperial",
    region: "Inland Empire",
    lat: 32.9790,
    lng: -115.5298,
    siteCount: 4,
    patientCount: "22,000+",
    staffCount: "120+",
    programs: ["ECM", "Community Supports", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.csdp.org",
    description:
      "Clinicas de Salud del Pueblo provides primary care, dental, preventive, and health promotion services to farmworker and immigrant communities in the Imperial Valley.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.csdp.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 50,
    fundingImpactLevel: "high",
    missionStatement: "Clinicas de Salud del Pueblo provides quality, comprehensive health services to residents of the Imperial and Coachella Valleys, regardless of ability to pay.",
  },
  {
    name: "Desert AIDS Project/DAP Health",
    slug: "desert-aids-project",
    city: "Palm Springs",
    county: "Riverside",
    region: "Inland Empire",
    lat: 33.8242,
    lng: -116.5436,
    siteCount: 3,
    patientCount: "11,000+",
    staffCount: "65+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.daphealth.org",
    description:
      "Desert AIDS Project provides comprehensive primary care, behavioral health, and specialty services with a focus on HIV/AIDS and sexual health for the Coachella Valley community.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.daphealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 10,
    fundingImpactLevel: "low",
    missionStatement: "DAP Health provides quality healthcare with a focus on HIV/AIDS and LGBTQ+ communities in the Coachella Valley.",
  },

  // ─────────────────────────────────────────────
  // CENTRAL COAST REGION (4)
  // ─────────────────────────────────────────────
  {
    name: "Community Health Centers of the Central Coast",
    slug: "community-health-centers-central-coast",
    city: "Santa Maria",
    county: "Santa Barbara",
    region: "Central Coast",
    lat: 34.9531,
    lng: -120.4357,
    siteCount: 15,
    patientCount: "75,000+",
    staffCount: "395+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.chccc.org",
    description:
      "Community Health Centers of the Central Coast provides primary care, dental, behavioral health, and pharmacy services to agricultural communities across Santa Barbara and San Luis Obispo counties.",
    glassdoorRating: 3.6,
    glassdoorReviewCount: 30,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.chccc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 30,
    fundingImpactLevel: "high",
    missionStatement: "Community Health Centers provides quality primary care to everyone in the Central Coast community, regardless of ability to pay.",
  },
  {
    name: "Dignity Health Community Clinics - Ventura",
    slug: "dignity-health-ventura",
    city: "Ventura",
    county: "Ventura",
    region: "Central Coast",
    lat: 34.2746,
    lng: -119.2931,
    siteCount: 6,
    patientCount: "32,000+",
    staffCount: "170+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "Cerner",
    website: "https://www.dignityhealth.org",
    description:
      "Dignity Health Community Clinics provides primary care, preventive services, and health education to underserved communities in Ventura County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.dignityhealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Dignity Health Community Clinics provides quality, compassionate healthcare to underserved communities in Ventura County.",
  },
  {
    name: "Clinicas del Camino Real",
    slug: "clinicas-del-camino-real",
    city: "Oxnard",
    county: "Ventura",
    region: "Central Coast",
    lat: 34.1964,
    lng: -119.1789,
    siteCount: 8,
    patientCount: "48,000+",
    staffCount: "250+",
    programs: ["ECM", "CCM", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.caminoreal.org",
    description:
      "Clinicas del Camino Real serves farmworker and migrant communities in Ventura County with primary care, dental, behavioral health, and occupational health services.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.caminoreal.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 35,
    fundingImpactLevel: "high",
    missionStatement: "Clinicas del Camino Real provides quality primary healthcare and support services to individuals and families regardless of their ability to pay.",
  },
  {
    name: "Santa Barbara Neighborhood Clinics",
    slug: "santa-barbara-neighborhood-clinics",
    city: "Santa Barbara",
    county: "Santa Barbara",
    region: "Central Coast",
    lat: 34.4208,
    lng: -119.6982,
    siteCount: 5,
    patientCount: "28,000+",
    staffCount: "150+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "eClinicalWorks",
    website: "https://www.sbnc.org",
    description:
      "Santa Barbara Neighborhood Clinics provides comprehensive primary care, dental, behavioral health, and health education services to diverse communities in Santa Barbara County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.sbnc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "Santa Barbara Neighborhood Clinics provides quality healthcare to all community members, regardless of ability to pay.",
  },

  // ─────────────────────────────────────────────
  // NORTH STATE REGION (6)
  // ─────────────────────────────────────────────
  {
    name: "Shasta Community Health Center",
    slug: "shasta-community-health-center",
    city: "Redding",
    county: "Shasta",
    region: "North State",
    lat: 40.5865,
    lng: -122.3917,
    siteCount: 6,
    patientCount: "35,000+",
    staffCount: "185+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.shastahealth.org",
    description:
      "Shasta Community Health Center provides comprehensive medical, dental, and behavioral health care to residents of the rural Northern California communities in Shasta County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.shastahealth.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Shasta Community Health Center provides quality, comprehensive healthcare to all in the Shasta County area.",
  },
  {
    name: "Peach Tree Health",
    slug: "peach-tree-health",
    city: "Marysville",
    county: "Yuba",
    region: "North State",
    lat: 39.1457,
    lng: -121.5908,
    siteCount: 6,
    patientCount: "32,000+",
    staffCount: "170+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.peachtreehealth.org",
    description:
      "Peach Tree Health provides primary care, dental, and behavioral health services to underserved communities in Yuba, Sutter, and surrounding rural Northern California counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://pickpeach.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Peach Tree Health provides quality healthcare to underserved communities in Yuba-Sutter.",
  },
  {
    name: "Health Alliance of Northern California",
    slug: "health-alliance-northern-california",
    city: "Redding",
    county: "Shasta",
    region: "North State",
    lat: 40.5897,
    lng: -122.3945,
    siteCount: 8,
    patientCount: "42,000+",
    staffCount: "220+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.hoanc.org",
    description:
      "Health Alliance of Northern California provides primary care, dental, and behavioral health services across rural northern counties including Shasta, Trinity, and Lassen.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.hoanc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Health Alliance of Northern California provides quality healthcare to rural communities in Northern California.",
  },
  {
    name: "Hill Country Community Clinic",
    slug: "hill-country-community-clinic",
    city: "Round Mountain",
    county: "Shasta",
    region: "North State",
    lat: 40.9281,
    lng: -121.5886,
    siteCount: 2,
    patientCount: "8,000+",
    staffCount: "45+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.hillcountryclinic.org",
    description:
      "Hill Country Community Clinic provides primary care and behavioral health services to rural mountain communities in northern Shasta County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.hillcountryclinic.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Hill Country Community Clinic provides quality healthcare to rural communities in Northern California.",
  },
  {
    name: "Shingletown Medical Center",
    slug: "shingletown-medical-center",
    city: "Shingletown",
    county: "Shasta",
    region: "North State",
    lat: 40.5080,
    lng: -121.8296,
    siteCount: 2,
    patientCount: "6,500+",
    staffCount: "40+",
    programs: ["ECM", "BH Integration"],
    ehrSystem: "NextGen",
    website: "https://www.shingletownmedical.org",
    description:
      "Shingletown Medical Center provides primary care and basic services to the remote mountain community of Shingletown in eastern Shasta County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.shingletownmedical.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Shingletown Medical Center provides quality healthcare to the rural communities of eastern Shasta County.",
  },

  // ─────────────────────────────────────────────
  // NORTH COAST REGION (4)
  // ─────────────────────────────────────────────
  {
    name: "Open Door Community Health Centers",
    slug: "open-door-community-health-centers",
    city: "Arcata",
    county: "Humboldt",
    region: "North Coast",
    lat: 40.8665,
    lng: -124.0828,
    siteCount: 9,
    patientCount: "50,000+",
    staffCount: "265+",
    programs: ["ECM", "CCM", "Community Supports", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.opendoorhealth.com",
    description:
      "Open Door Community Health Centers provides medical, dental, and behavioral health care to rural communities along the North Coast of California in Humboldt and Del Norte counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.opendoorhealth.com/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Open Door Community Health Centers provides quality healthcare to the communities of the North Coast.",
  },
  {
    name: "MCHC Health Centers",
    slug: "mchc-health-centers",
    city: "Ukiah",
    county: "Mendocino",
    region: "North Coast",
    lat: 39.1659,
    lng: -123.2076,
    siteCount: 7,
    patientCount: "38,000+",
    staffCount: "200+",
    programs: ["ECM", "CCM", "BH Integration", "Community Supports"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.mchcinc.org",
    description:
      "MCHC Health Centers provides comprehensive primary care, dental, behavioral health, and specialty services to underserved communities in Mendocino and Lake counties.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.mchcinc.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "MCHC Health Centers provides quality healthcare to the communities of Lake and Mendocino counties.",
  },
  {
    name: "Redwood Community Health Coalition",
    slug: "redwood-community-health-coalition",
    city: "Fortuna",
    county: "Humboldt",
    region: "North Coast",
    lat: 40.5979,
    lng: -124.1618,
    siteCount: 4,
    patientCount: "22,000+",
    staffCount: "120+",
    programs: ["ECM", "BH Integration", "Community Supports"],
    ehrSystem: "NextGen",
    website: "https://www.rchc-health.org",
    description:
      "Redwood Community Health Coalition member clinics provide primary care, dental, and behavioral health services to communities throughout southern Humboldt County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.rchc-health.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 5,
    fundingImpactLevel: "low",
    missionStatement: "Redwood Community Health Coalition provides quality healthcare to underserved communities in Sonoma County.",
  },
  {
    name: "San Luis Obispo Community Health Centers",
    slug: "san-luis-obispo-community-health-centers",
    city: "San Luis Obispo",
    county: "San Luis Obispo",
    region: "North Coast",
    lat: 35.2828,
    lng: -120.6626,
    siteCount: 6,
    patientCount: "32,000+",
    staffCount: "170+",
    programs: ["ECM", "CCM", "BH Integration"],
    ehrSystem: "OCHIN Epic",
    website: "https://www.slohealthcenter.org",
    description:
      "San Luis Obispo Community Health Centers provides primary care, dental, behavioral health, and preventive services to diverse communities across San Luis Obispo County.",
    glassdoorRating: null,
    glassdoorReviewCount: null,
    ecmProvider: true,
    nhscApproved: true,
    careersUrl: "https://www.slohealthcenter.org/careers/",
    servesUndocumented: true,
    coverageVulnerabilityPercent: 15,
    fundingImpactLevel: "moderate",
    missionStatement: "San Luis Obispo Community Health Centers provides quality healthcare to all, regardless of ability to pay.",
  },
];
