// Career pathway data for California FQHCs
// 6 career tracks with 4 levels each, CA-specific salary ranges and certifications

export interface CareerLevel {
  roleId: string;
  title: string;
  esTitle: string;
  salaryP25: number;
  salaryP50: number;
  salaryP75: number;
  yearsExperience: string;
  esYearsExperience: string;
  certifications: string[];
  esCertifications: string[];
  keySkills: string[];
  esKeySkills: string[];
  programs: string[];
}

export interface CareerPathway {
  id: string;
  name: string;
  esName: string;
  description: string;
  esDescription: string;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
  levels: CareerLevel[];
}

export interface RegionalMultiplier {
  region: string;
  esRegion: string;
  multiplier: number;
  description: string;
  esDescription: string;
}

// California regional salary multipliers based on cost-of-living differences
export const REGIONAL_MULTIPLIERS: RegionalMultiplier[] = [
  {
    region: "SF Bay Area",
    esRegion: "Área de la Bahía de SF",
    multiplier: 1.15,
    description: "Highest cost of living in CA. FQHCs compete with tech for talent.",
    esDescription: "Mayor costo de vida en CA. Los FQHCs compiten con la tecnología por talento.",
  },
  {
    region: "Los Angeles",
    esRegion: "Los Ángeles",
    multiplier: 1.08,
    description: "Large FQHC market. 60+ health centers across LA County.",
    esDescription: "Gran mercado de FQHCs. Más de 60 centros de salud en el condado de LA.",
  },
  {
    region: "San Diego",
    esRegion: "San Diego",
    multiplier: 1.05,
    description: "Growing FQHC network. Bilingual Spanish strongly valued.",
    esDescription: "Red creciente de FQHCs. Se valora mucho el bilingüismo en español.",
  },
  {
    region: "Central Coast",
    esRegion: "Costa Central",
    multiplier: 1.02,
    description: "Santa Barbara, San Luis Obispo, Monterey. Rural access challenges.",
    esDescription: "Santa Bárbara, San Luis Obispo, Monterey. Desafíos de acceso rural.",
  },
  {
    region: "Sacramento",
    esRegion: "Sacramento",
    multiplier: 1.0,
    description: "State capital baseline. Strong government health programs.",
    esDescription: "Base de la capital estatal. Fuertes programas gubernamentales de salud.",
  },
  {
    region: "Inland Empire",
    esRegion: "Inland Empire",
    multiplier: 0.95,
    description: "Riverside & San Bernardino. High demand, under-resourced communities.",
    esDescription: "Riverside y San Bernardino. Alta demanda, comunidades con acceso limitado a la atenci\u00f3n.",
  },
  {
    region: "Central Valley",
    esRegion: "Valle Central",
    multiplier: 0.92,
    description: "Fresno, Bakersfield, Stockton. Critical shortage areas. Bilingual essential.",
    esDescription: "Fresno, Bakersfield, Stockton. Áreas de escasez crítica. Bilingüismo esencial.",
  },
  {
    region: "North State",
    esRegion: "Norte del Estado",
    multiplier: 0.9,
    description: "Redding, Chico. Rural FQHCs with NHSC loan repayment eligibility.",
    esDescription: "Redding, Chico. FQHCs rurales con elegibilidad de pago de préstamos NHSC.",
  },
  {
    region: "North Coast",
    esRegion: "Costa Norte",
    multiplier: 0.88,
    description: "Humboldt, Mendocino. Most remote, tribal health partnerships.",
    esDescription: "Humboldt, Mendocino. Más remotos, alianzas de salud tribal.",
  },
];

export const CAREER_PATHWAYS: CareerPathway[] = [
  {
    id: "community-health",
    name: "Community Health",
    esName: "Salud Comunitaria",
    description: "From frontline community work to directing programs that serve thousands.",
    esDescription: "Del trabajo comunitario en primera línea a dirigir programas que atienden a miles.",
    icon: "Heart",
    color: "teal",
    levels: [
      {
        roleId: "chw",
        title: "Community Health Worker",
        esTitle: "Promotor(a) de Salud",
        salaryP25: 44000,
        salaryP50: 52000,
        salaryP75: 62000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["CA CHW Certificate (CDPH)"],
        esCertifications: ["Certificado de CHW de California (CDPH)"],
        keySkills: [
          "Community outreach",
          "Health education",
          "Motivational interviewing",
          "Bilingual communication",
          "Resource navigation",
        ],
        esKeySkills: [
          "Alcance comunitario",
          "Educación en salud",
          "Entrevista motivacional",
          "Comunicación bilingüe",
          "Navegación de recursos",
        ],
        programs: ["CalAIM ECM", "Medi-Cal", "WIC"],
      },
      {
        roleId: "care_coordinator",
        title: "Care Coordinator",
        esTitle: "Coordinador(a) de Cuidado",
        salaryP25: 48000,
        salaryP50: 58000,
        salaryP75: 68000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CCM (optional)", "CalAIM ECM Training"],
        esCertifications: ["CCM (opcional)", "Capacitación CalAIM ECM"],
        keySkills: [
          "Care plan development",
          "Multi-provider coordination",
          "EHR documentation (OCHIN Epic)",
          "Patient advocacy",
          "Data tracking & reporting",
        ],
        esKeySkills: [
          "Desarrollo de planes de cuidado",
          "Coordinación multi-proveedor",
          "Documentación EHR (OCHIN Epic)",
          "Defensa del paciente",
          "Seguimiento de datos e informes",
        ],
        programs: ["CalAIM ECM/CCM", "Medi-Cal Managed Care", "HEDIS measures"],
      },
      {
        roleId: "program-manager",
        title: "Program Manager",
        esTitle: "Gerente de Programa",
        salaryP25: 68000,
        salaryP50: 85000,
        salaryP75: 100000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["PMP (optional)", "CCM"],
        esCertifications: ["PMP (opcional)", "CCM"],
        keySkills: [
          "Team supervision",
          "Grant writing & compliance",
          "Program evaluation",
          "Budget management",
          "Stakeholder engagement",
        ],
        esKeySkills: [
          "Supervisión de equipo",
          "Redacción de subvenciones y cumplimiento",
          "Evaluación de programas",
          "Gestión de presupuesto",
          "Participación de partes interesadas",
        ],
        programs: ["HRSA UDS reporting", "CalAIM", "340B"],
      },
      {
        roleId: "director-community",
        title: "Director of Community Programs",
        esTitle: "Director(a) de Programas Comunitarios",
        salaryP25: 95000,
        salaryP50: 118000,
        salaryP75: 140000,
        yearsExperience: "7+ years",
        esYearsExperience: "7+ años",
        certifications: ["MPH or MPA (preferred)"],
        esCertifications: ["MPH o MPA (preferido)"],
        keySkills: [
          "Strategic planning",
          "Cross-department leadership",
          "Board reporting",
          "Community partnerships",
          "Policy advocacy",
        ],
        esKeySkills: [
          "Planificación estratégica",
          "Liderazgo interdepartamental",
          "Informes a la junta",
          "Alianzas comunitarias",
          "Defensa de políticas",
        ],
        programs: ["FQHC look-alike designation", "PCMH", "ACO partnerships"],
      },
    ],
  },
  {
    id: "clinical-operations",
    name: "Clinical Operations",
    esName: "Operaciones Clínicas",
    description: "From medical assisting to leading clinical teams and operations.",
    esDescription: "De asistencia médica a liderar equipos y operaciones clínicas.",
    icon: "Stethoscope",
    color: "blue",
    levels: [
      {
        roleId: "medical_assistant",
        title: "Medical Assistant",
        esTitle: "Asistente Médico",
        salaryP25: 44000,
        salaryP50: 50000,
        salaryP75: 58000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["CMA (AAMA) or RMA", "BLS/CPR"],
        esCertifications: ["CMA (AAMA) o RMA", "BLS/CPR"],
        keySkills: [
          "Vitals & patient intake",
          "EHR data entry (OCHIN Epic)",
          "Phlebotomy",
          "Bilingual patient communication",
          "Exam room preparation",
        ],
        esKeySkills: [
          "Signos vitales e ingreso de pacientes",
          "Entrada de datos EHR (OCHIN Epic)",
          "Flebotomía",
          "Comunicación bilingüe con pacientes",
          "Preparación de sala de examen",
        ],
        programs: ["PCMH workflows", "Immunization tracking"],
      },
      {
        roleId: "lead-ma",
        title: "Lead Medical Assistant",
        esTitle: "Asistente Médico Líder",
        salaryP25: 48000,
        salaryP50: 55000,
        salaryP75: 64000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CMA", "BLS", "OCHIN Epic proficiency"],
        esCertifications: ["CMA", "BLS", "Competencia en OCHIN Epic"],
        keySkills: [
          "MA team scheduling",
          "Training new MAs",
          "Inventory management",
          "Quality improvement",
          "Provider support coordination",
        ],
        esKeySkills: [
          "Programación del equipo de MA",
          "Capacitación de nuevos MAs",
          "Gestión de inventario",
          "Mejora de calidad",
          "Coordinación de apoyo a proveedores",
        ],
        programs: ["HEDIS measures", "Patient-Centered Medical Home"],
      },
      {
        roleId: "clinical-ops-supervisor",
        title: "Clinical Operations Supervisor",
        esTitle: "Supervisor(a) de Operaciones Clínicas",
        salaryP25: 60000,
        salaryP50: 72000,
        salaryP75: 85000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["Healthcare management certificate (optional)"],
        esCertifications: ["Certificado de gestión sanitaria (opcional)"],
        keySkills: [
          "Workflow optimization",
          "Staff performance management",
          "Regulatory compliance (OSHA, HIPAA)",
          "Patient throughput analysis",
          "Cross-site coordination",
        ],
        esKeySkills: [
          "Optimización de flujo de trabajo",
          "Gestión del desempeño del personal",
          "Cumplimiento regulatorio (OSHA, HIPAA)",
          "Análisis de flujo de pacientes",
          "Coordinación entre sitios",
        ],
        programs: ["UDS reporting", "Joint Commission prep"],
      },
      {
        roleId: "director-clinical-ops",
        title: "Director of Clinical Operations",
        esTitle: "Director(a) de Operaciones Clínicas",
        salaryP25: 88000,
        salaryP50: 108000,
        salaryP75: 130000,
        yearsExperience: "7+ years",
        esYearsExperience: "7+ años",
        certifications: ["MHA or MBA (preferred)"],
        esCertifications: ["MHA o MBA (preferido)"],
        keySkills: [
          "Multi-site management",
          "Strategic capacity planning",
          "EHR system optimization",
          "Provider recruitment strategy",
          "Board-level reporting",
        ],
        esKeySkills: [
          "Gestión multi-sitio",
          "Planificación estratégica de capacidad",
          "Optimización del sistema EHR",
          "Estrategia de reclutamiento de proveedores",
          "Informes a nivel de junta",
        ],
        programs: ["FQHC compliance (HRSA)", "340B administration"],
      },
    ],
  },
  {
    id: "behavioral-health",
    name: "Behavioral Health",
    esName: "Salud Conductual",
    description: "From behavioral health support to leading integrated care programs.",
    esDescription: "Del apoyo en salud conductual a liderar programas de cuidado integrado.",
    icon: "Brain",
    color: "purple",
    levels: [
      {
        roleId: "bh-technician",
        title: "Behavioral Health Technician",
        esTitle: "Técnico de Salud Conductual",
        salaryP25: 44000,
        salaryP50: 50000,
        salaryP75: 58000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["BLS/CPR", "Trauma-Informed Care training"],
        esCertifications: ["BLS/CPR", "Capacitación en cuidado informado por trauma"],
        keySkills: [
          "Crisis de-escalation",
          "Group facilitation",
          "Screening tools (PHQ-9, GAD-7)",
          "Safety planning",
          "Bilingual support",
        ],
        esKeySkills: [
          "Desescalada de crisis",
          "Facilitación de grupos",
          "Herramientas de detección (PHQ-9, GAD-7)",
          "Planificación de seguridad",
          "Apoyo bilingüe",
        ],
        programs: ["BH-ASO", "SBIRT screening"],
      },
      {
        roleId: "behavioral_health",
        title: "Behavioral Health Specialist",
        esTitle: "Especialista en Salud Conductual",
        salaryP25: 55000,
        salaryP50: 70000,
        salaryP75: 85000,
        yearsExperience: "2–3 years",
        esYearsExperience: "2–3 años",
        certifications: ["AMFT or APCC (CA BBS)", "Motivational Interviewing"],
        esCertifications: ["AMFT o APCC (CA BBS)", "Entrevista Motivacional"],
        keySkills: [
          "Individual & group therapy",
          "Integrated care model",
          "Clinical documentation",
          "Warm handoffs with PCPs",
          "Cultural competency",
        ],
        esKeySkills: [
          "Terapia individual y grupal",
          "Modelo de cuidado integrado",
          "Documentación clínica",
          "Transiciones cálidas con PCPs",
          "Competencia cultural",
        ],
        programs: ["CalAIM BH services", "Medi-Cal BH carve-in"],
      },
      {
        roleId: "licensed-therapist",
        title: "Licensed Therapist (LCSW/LMFT)",
        esTitle: "Terapeuta con Licencia (LCSW/LMFT)",
        salaryP25: 78000,
        salaryP50: 92000,
        salaryP75: 110000,
        yearsExperience: "4–6 years",
        esYearsExperience: "4–6 años",
        certifications: ["LCSW or LMFT (CA BBS)", "NHSC eligible"],
        esCertifications: ["LCSW o LMFT (CA BBS)", "Elegible para NHSC"],
        keySkills: [
          "Clinical supervision of pre-licensed staff",
          "Evidence-based treatment (CBT, DBT, MI)",
          "Complex case consultation",
          "Community referral network",
          "Telehealth delivery",
        ],
        esKeySkills: [
          "Supervisión clínica de personal pre-licenciado",
          "Tratamiento basado en evidencia (CBT, DBT, MI)",
          "Consulta de casos complejos",
          "Red de referencia comunitaria",
          "Entrega de telesalud",
        ],
        programs: ["NHSC Loan Repayment ($50-75K)", "CalAIM ECM BH"],
      },
      {
        roleId: "bh-director",
        title: "Behavioral Health Director",
        esTitle: "Director(a) de Salud Conductual",
        salaryP25: 100000,
        salaryP50: 130000,
        salaryP75: 160000,
        yearsExperience: "8+ years",
        esYearsExperience: "8+ años",
        certifications: ["LCSW/LMFT", "Clinical Supervisor credential"],
        esCertifications: ["LCSW/LMFT", "Credencial de Supervisor Clínico"],
        keySkills: [
          "Department budget management",
          "Integrated BH program development",
          "Staff recruitment & retention",
          "Outcomes measurement",
          "Payer contract negotiation",
        ],
        esKeySkills: [
          "Gestión de presupuesto departamental",
          "Desarrollo de programas BH integrados",
          "Reclutamiento y retención de personal",
          "Medición de resultados",
          "Negociación de contratos con pagadores",
        ],
        programs: ["CCBHC designation", "Medi-Cal BH managed care"],
      },
    ],
  },
  {
    id: "revenue-admin",
    name: "Revenue & Administration",
    esName: "Ingresos y Administración",
    description: "From front desk to financial leadership — the business backbone of FQHCs.",
    esDescription: "De la recepción al liderazgo financiero — la columna vertebral de los FQHCs.",
    icon: "DollarSign",
    color: "amber",
    levels: [
      {
        roleId: "patient_services",
        title: "Patient Services Representative",
        esTitle: "Representante de Servicios al Paciente",
        salaryP25: 44000,
        salaryP50: 48000,
        salaryP75: 55000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["OCHIN Epic front desk training"],
        esCertifications: ["Capacitación de recepción OCHIN Epic"],
        keySkills: [
          "Patient registration",
          "Insurance verification (Medi-Cal, Medicare)",
          "Appointment scheduling",
          "Sliding fee scale enrollment",
          "Bilingual front desk",
        ],
        esKeySkills: [
          "Registro de pacientes",
          "Verificación de seguros (Medi-Cal, Medicare)",
          "Programación de citas",
          "Inscripción en escala de tarifas variables",
          "Recepción bilingüe",
        ],
        programs: ["Sliding Fee Scale", "Medi-Cal eligibility"],
      },
      {
        roleId: "revenue_cycle",
        title: "Revenue Cycle Specialist",
        esTitle: "Especialista en Ciclo de Ingresos",
        salaryP25: 52000,
        salaryP50: 65000,
        salaryP75: 78000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CPC (AAPC)", "OCHIN Epic Certification"],
        esCertifications: ["CPC (AAPC)", "Certificación OCHIN Epic"],
        keySkills: [
          "Medical coding (ICD-10, CPT)",
          "Claims submission & denial management",
          "PPS rate optimization",
          "A/R follow-up",
          "Compliance auditing",
        ],
        esKeySkills: [
          "Codificación médica (ICD-10, CPT)",
          "Envío de reclamos y gestión de denegaciones",
          "Optimización de tarifas PPS",
          "Seguimiento de cuentas por cobrar",
          "Auditoría de cumplimiento",
        ],
        programs: ["FQHC PPS reimbursement", "340B"],
      },
      {
        roleId: "revenue-manager",
        title: "Revenue Cycle Manager",
        esTitle: "Gerente de Ciclo de Ingresos",
        salaryP25: 70000,
        salaryP50: 85000,
        salaryP75: 100000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["CPC", "CHFP (optional)"],
        esCertifications: ["CPC", "CHFP (opcional)"],
        keySkills: [
          "Team management",
          "Revenue forecasting",
          "Payer contract analysis",
          "Process improvement",
          "EHR revenue module administration",
        ],
        esKeySkills: [
          "Gestión de equipo",
          "Pronóstico de ingresos",
          "Análisis de contratos con pagadores",
          "Mejora de procesos",
          "Administración del módulo de ingresos EHR",
        ],
        programs: ["UDS financial reporting", "FQHC Cost Report"],
      },
      {
        roleId: "director-finance",
        title: "Director of Finance / CFO",
        esTitle: "Director(a) de Finanzas / CFO",
        salaryP25: 110000,
        salaryP50: 145000,
        salaryP75: 185000,
        yearsExperience: "8+ years",
        esYearsExperience: "8+ años",
        certifications: ["CPA or MBA/MHA (preferred)"],
        esCertifications: ["CPA o MBA/MHA (preferido)"],
        keySkills: [
          "Financial strategy & planning",
          "Grant financial management (HRSA)",
          "Board financial reporting",
          "Audit coordination",
          "Multi-site financial operations",
        ],
        esKeySkills: [
          "Estrategia y planificación financiera",
          "Gestión financiera de subvenciones (HRSA)",
          "Informes financieros a la junta",
          "Coordinación de auditorías",
          "Operaciones financieras multi-sitio",
        ],
        programs: ["HRSA grant compliance", "340B optimization", "FQHC Cost Report"],
      },
    ],
  },
  {
    id: "back-office",
    name: "Back Office & Finance",
    esName: "Oficina Administrativa y Finanzas",
    description: "From accounting and payroll to financial leadership — the administrative engine that keeps FQHCs running.",
    esDescription: "De contabilidad y nómina al liderazgo financiero — el motor administrativo que mantiene funcionando a los FQHCs.",
    icon: "Briefcase",
    color: "indigo",
    levels: [
      {
        roleId: "payroll_specialist",
        title: "Payroll Specialist / Accounting Clerk",
        esTitle: "Especialista en Nómina / Auxiliar Contable",
        salaryP25: 52000,
        salaryP50: 62000,
        salaryP75: 75000,
        yearsExperience: "Entry level – 1 year",
        esYearsExperience: "Nivel de entrada – 1 año",
        certifications: ["FPC (Fundamental Payroll Certification)", "ADP or Paychex certification"],
        esCertifications: ["FPC (Certificación Fundamental de Nómina)", "Certificación ADP o Paychex"],
        keySkills: [
          "Multi-site payroll processing",
          "California wage & hour compliance",
          "Payroll system administration (ADP, Paychex)",
          "Garnishment and deduction management",
          "Tax filing and reconciliation",
        ],
        esKeySkills: [
          "Procesamiento de nómina multi-sitio",
          "Cumplimiento de salarios y horas de California",
          "Administración de sistemas de nómina (ADP, Paychex)",
          "Gestión de embargos y deducciones",
          "Declaración fiscal y conciliación",
        ],
        programs: ["SB 525 compliance", "Union CBA wage scales"],
      },
      {
        roleId: "accountant",
        title: "Accountant / HR Manager",
        esTitle: "Contador(a) / Gerente de RH",
        salaryP25: 60000,
        salaryP50: 78000,
        salaryP75: 98000,
        yearsExperience: "2–4 years",
        esYearsExperience: "2–4 años",
        certifications: ["CPA (preferred)", "PHR/SHRM-CP (for HR track)", "340B University (Apexus)"],
        esCertifications: ["CPA (preferido)", "PHR/SHRM-CP (para trayectoria de RH)", "Universidad 340B (Apexus)"],
        keySkills: [
          "Grant accounting and cost allocation",
          "Financial statement preparation",
          "Audit preparation (HRSA, single audit)",
          "Healthcare recruitment and retention",
          "Union labor relations",
        ],
        esKeySkills: [
          "Contabilidad de subvenciones y asignación de costos",
          "Preparación de estados financieros",
          "Preparación de auditorías (HRSA, auditoría única)",
          "Reclutamiento y retención en salud",
          "Relaciones laborales sindicales",
        ],
        programs: ["HRSA grant compliance", "340B accounting", "SB 525 implementation"],
      },
      {
        roleId: "finance_manager",
        title: "Finance Manager / Controller",
        esTitle: "Gerente de Finanzas / Contralor",
        salaryP25: 90000,
        salaryP50: 108000,
        salaryP75: 130000,
        yearsExperience: "5–7 years",
        esYearsExperience: "5–7 años",
        certifications: ["CPA", "CHFP (Certified Healthcare Financial Professional)", "MBA/MHA (preferred)"],
        esCertifications: ["CPA", "CHFP (Profesional Financiero de Salud Certificado)", "MBA/MHA (preferido)"],
        keySkills: [
          "Financial modeling and forecasting",
          "Cash flow management and treasury",
          "Board-level financial reporting",
          "Payer contract analysis",
          "Multi-source revenue management",
        ],
        esKeySkills: [
          "Modelado y pronóstico financiero",
          "Gestión de flujo de efectivo y tesorería",
          "Informes financieros a nivel de junta",
          "Análisis de contratos con pagadores",
          "Gestión de ingresos de múltiples fuentes",
        ],
        programs: ["CalAIM financial modeling", "UDS financial reporting", "FQHC Cost Report"],
      },
      {
        roleId: "director-finance",
        title: "Director of Finance / CFO",
        esTitle: "Director(a) de Finanzas / CFO",
        salaryP25: 130000,
        salaryP50: 165000,
        salaryP75: 200000,
        yearsExperience: "8+ years",
        esYearsExperience: "8+ años",
        certifications: ["CPA", "MBA or MHA", "FQHC financial leadership experience"],
        esCertifications: ["CPA", "MBA o MHA", "Experiencia en liderazgo financiero FQHC"],
        keySkills: [
          "Organizational financial strategy",
          "C-suite leadership",
          "Grant portfolio management ($10M+)",
          "Board governance and fiduciary oversight",
          "Revenue diversification strategy",
        ],
        esKeySkills: [
          "Estrategia financiera organizacional",
          "Liderazgo de nivel ejecutivo",
          "Gestión de portafolio de subvenciones ($10M+)",
          "Gobernanza de junta y supervisión fiduciaria",
          "Estrategia de diversificación de ingresos",
        ],
        programs: ["HRSA strategic planning", "340B optimization", "CalAIM Community Supports"],
      },
    ],
  },
  {
    id: "nursing",
    name: "Nursing & Clinical Leadership",
    esName: "Enfermería y Liderazgo Clínico",
    description: "From bedside nursing to leading entire clinical organizations.",
    esDescription: "De enfermería clínica a liderar organizaciones clínicas completas.",
    icon: "Activity",
    color: "rose",
    levels: [
      {
        roleId: "registered_nurse",
        title: "Registered Nurse (RN)",
        esTitle: "Enfermero(a) Registrado(a) (RN)",
        salaryP25: 90000,
        salaryP50: 110000,
        salaryP75: 130000,
        yearsExperience: "Entry level (BSN)",
        esYearsExperience: "Nivel de entrada (BSN)",
        certifications: ["RN License (CA BRN)", "BLS/CPR", "BSN (preferred)"],
        esCertifications: ["Licencia RN (CA BRN)", "BLS/CPR", "BSN (preferido)"],
        keySkills: [
          "Patient assessment & triage",
          "Medication administration",
          "Care coordination",
          "EHR documentation (OCHIN Epic)",
          "Patient education",
        ],
        esKeySkills: [
          "Evaluación y triaje de pacientes",
          "Administración de medicamentos",
          "Coordinación de cuidado",
          "Documentación EHR (OCHIN Epic)",
          "Educación del paciente",
        ],
        programs: ["NHSC Loan Repayment", "CalAIM clinical programs"],
      },
      {
        roleId: "charge-nurse",
        title: "Charge Nurse",
        esTitle: "Enfermero(a) a Cargo",
        salaryP25: 95000,
        salaryP50: 115000,
        salaryP75: 140000,
        yearsExperience: "2–3 years",
        esYearsExperience: "2–3 años",
        certifications: ["BSN", "BLS/ACLS", "OCHIN Epic proficiency"],
        esCertifications: ["BSN", "BLS/ACLS", "Competencia en OCHIN Epic"],
        keySkills: [
          "Shift management",
          "Clinical staff scheduling",
          "Quality metric tracking",
          "New nurse mentoring",
          "Emergency response leadership",
        ],
        esKeySkills: [
          "Gestión de turnos",
          "Programación de personal clínico",
          "Seguimiento de métricas de calidad",
          "Mentoría de enfermeros nuevos",
          "Liderazgo de respuesta a emergencias",
        ],
        programs: ["HEDIS quality measures", "Patient safety protocols"],
      },
      {
        roleId: "nurse-manager",
        title: "Nurse Manager",
        esTitle: "Gerente de Enfermería",
        salaryP25: 110000,
        salaryP50: 130000,
        salaryP75: 155000,
        yearsExperience: "5–7 years",
        esYearsExperience: "5–7 años",
        certifications: ["MSN (preferred)", "Nurse Executive certification (optional)"],
        esCertifications: ["MSN (preferido)", "Certificación de ejecutivo de enfermería (opcional)"],
        keySkills: [
          "Department budget management",
          "Staff recruitment & retention",
          "Clinical protocol development",
          "Interdisciplinary team leadership",
          "Performance improvement",
        ],
        esKeySkills: [
          "Gestión de presupuesto departamental",
          "Reclutamiento y retención de personal",
          "Desarrollo de protocolos clínicos",
          "Liderazgo de equipo interdisciplinario",
          "Mejora del desempeño",
        ],
        programs: ["Joint Commission readiness", "PCMH standards"],
      },
      {
        roleId: "cno",
        title: "Chief Nursing Officer (CNO)",
        esTitle: "Director(a) de Enfermería (CNO)",
        salaryP25: 130000,
        salaryP50: 165000,
        salaryP75: 200000,
        yearsExperience: "10+ years",
        esYearsExperience: "10+ años",
        certifications: ["DNP or MSN", "NEA-BC (optional)"],
        esCertifications: ["DNP o MSN", "NEA-BC (opcional)"],
        keySkills: [
          "Organizational nursing strategy",
          "C-suite leadership",
          "Clinical quality & safety oversight",
          "Workforce planning",
          "Community health partnerships",
        ],
        esKeySkills: [
          "Estrategia organizacional de enfermería",
          "Liderazgo de nivel ejecutivo",
          "Supervisión de calidad y seguridad clínica",
          "Planificación de fuerza laboral",
          "Alianzas de salud comunitaria",
        ],
        programs: ["HRSA strategic planning", "ACO/VBC models"],
      },
    ],
  },
  {
    id: "compliance-operations",
    name: "Compliance & Risk Operations",
    esName: "Cumplimiento y Operaciones de Riesgo",
    description: "From audit support to leading enterprise risk management and regulatory compliance.",
    esDescription: "De apoyo de auditoría a liderar gestión de riesgos empresariales y cumplimiento regulatorio.",
    icon: "CheckCircle",
    color: "cyan",
    levels: [
      {
        roleId: "compliance_analyst",
        title: "Compliance Analyst",
        esTitle: "Analista de Cumplimiento",
        salaryP25: 50000,
        salaryP50: 65000,
        salaryP75: 80000,
        yearsExperience: "0–2 years",
        esYearsExperience: "0–2 años",
        certifications: ["HIPAA Training", "CHC (Community Health Certification) preferred"],
        esCertifications: ["Capacitación HIPAA", "CHC (Certificación de Salud Comunitaria) preferido"],
        keySkills: [
          "HRSA OSV audit preparation",
          "HIPAA Privacy & Security Rule basics",
          "PPS billing compliance",
          "Policy documentation",
          "Audit trail support",
          "Staff training coordination",
        ],
        esKeySkills: [
          "Preparación para auditoría OSV de HRSA",
          "Conceptos básicos de Privacidad y Seguridad HIPAA",
          "Cumplimiento de facturación PPS",
          "Documentación de políticas",
          "Apoyo a seguimiento de auditoría",
          "Coordinación de capacitación del personal",
        ],
        programs: ["HIPAA covered entity requirements", "HRSA 330 grant compliance"],
      },
      {
        roleId: "senior_compliance_analyst",
        title: "Senior Compliance Analyst",
        esTitle: "Analista Senior de Cumplimiento",
        salaryP25: 62000,
        salaryP50: 78000,
        salaryP75: 95000,
        yearsExperience: "2–5 years",
        esYearsExperience: "2–5 años",
        certifications: ["CHC (Certified Health Compliance)", "HIPAA Security Certification"],
        esCertifications: ["CHC (Certificado en Cumplimiento de Salud)", "Certificación de Seguridad HIPAA"],
        keySkills: [
          "Risk assessment & mitigation",
          "Policy development & maintenance",
          "340B program compliance monitoring",
          "Breach response protocols",
          "Internal audit coordination",
          "Staff training & education",
        ],
        esKeySkills: [
          "Evaluación de riesgos y mitigación",
          "Desarrollo y mantenimiento de políticas",
          "Monitoreo de cumplimiento del programa 340B",
          "Protocolos de respuesta a violaciones",
          "Coordinación de auditoría interna",
          "Educación y capacitación del personal",
        ],
        programs: ["340B Program Compliance", "HIPAA Breach Notification Rule", "CalAIM regulatory requirements"],
      },
      {
        roleId: "compliance_manager",
        title: "Compliance Manager",
        esTitle: "Gerente de Cumplimiento",
        salaryP25: 75000,
        salaryP50: 95000,
        salaryP75: 115000,
        yearsExperience: "5–10 years",
        esYearsExperience: "5–10 años",
        certifications: ["CHC", "CHPC (Certified Healthcare Compliance Professional)", "PPS Billing Compliance"],
        esCertifications: ["CHC", "CHPC (Profesional Certificado en Cumplimiento de Salud)", "Cumplimiento de Facturación PPS"],
        keySkills: [
          "HRSA OSV audit leadership",
          "Risk management strategy",
          "Workers' compensation compliance",
          "Incident investigation & documentation",
          "Board governance & reporting",
          "Staff training program development",
          "CalAIM compliance management",
        ],
        esKeySkills: [
          "Liderazgo en auditoría OSV de HRSA",
          "Estrategia de gestión de riesgos",
          "Cumplimiento de compensación de trabajadores",
          "Investigación de incidentes y documentación",
          "Gobernanza de junta e informes",
          "Desarrollo de programas de capacitación del personal",
          "Gestión del cumplimiento CalAIM",
        ],
        programs: ["HRSA Compliance Program", "HIPAA Compliance Officer Role", "CMS OIG Exclusion Monitoring"],
      },
      {
        roleId: "compliance_officer",
        title: "Chief Compliance Officer / Director",
        esTitle: "Director(a) de Cumplimiento / Oficial de Cumplimiento",
        salaryP25: 100000,
        salaryP50: 130000,
        salaryP75: 165000,
        yearsExperience: "10+ years",
        esYearsExperience: "10+ años",
        certifications: ["CHC", "CCEP (Certified Compliance and Ethics Professional)", "CHPC"],
        esCertifications: ["CHC", "CCEP (Profesional Certificado en Cumplimiento y Ética)", "CHPC"],
        keySkills: [
          "Enterprise risk management",
          "Regulatory strategy & advocacy",
          "C-suite leadership & board reporting",
          "OSV/audit defense strategy",
          "Compliance program design & implementation",
          "Policy governance",
          "Workforce compliance culture building",
          "Multi-site compliance coordination",
        ],
        esKeySkills: [
          "Gestión de riesgos empresariales",
          "Estrategia regulatoria y defensa",
          "Liderazgo de nivel ejecutivo e informes a junta",
          "Estrategia de defensa de auditoría/OSV",
          "Diseño e implementación de programas de cumplimiento",
          "Gobernanza de políticas",
          "Construcción de cultura de cumplimiento de fuerza laboral",
          "Coordinación de cumplimiento multi-sitio",
        ],
        programs: ["FQHC Compliance Program Excellence", "HRSA Strategic Compliance Planning", "Board-level Risk Oversight"],
      },
    ],
  },
  {
    id: "dental",
    name: "Dental & Oral Health",
    esName: "Dental y Salud Oral",
    description: "From chair-side assisting to leading a multi-site dental program that closes oral health gaps for under-resourced communities.",
    esDescription: "De asistencia chairside a liderar un programa dental multi-sitio que cierra las brechas de salud oral para comunidades con acceso limitado a la atenci\u00f3n.",
    icon: "Smile",
    color: "cyan",
    levels: [
      {
        roleId: "dental_assistant",
        title: "Dental Assistant (DA/RDA)",
        esTitle: "Asistente Dental (DA/RDA)",
        salaryP25: 44000,
        salaryP50: 52000,
        salaryP75: 60000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: [
          "California Dental Assistant certificate",
          "CA Radiation Safety Certificate (required)",
          "CPR/BLS",
          "RDA license (preferred — unlocks expanded duties)",
        ],
        esCertifications: [
          "Certificado de Asistente Dental de California",
          "Certificado de Seguridad de Radiación de CA (requerido)",
          "CPR/BLS",
          "Licencia RDA (preferida — desbloquea deberes ampliados)",
        ],
        keySkills: [
          "Chair-side assisting & instrument passing",
          "Dental radiograph exposure",
          "Infection control & sterilization",
          "Patient anxiety management",
          "Dental EHR documentation (Dentrix, Eaglesoft, Curve Dental)",
        ],
        esKeySkills: [
          "Asistencia chairside y pase de instrumentos",
          "Exposición de radiografías dentales",
          "Control de infecciones y esterilización",
          "Manejo de ansiedad del paciente",
          "Documentación en EHR dental (Dentrix, Eaglesoft, Curve Dental)",
        ],
        programs: ["Denti-Cal", "CHDP"],
      },
      {
        roleId: "dental_hygienist",
        title: "Dental Hygienist (RDH)",
        esTitle: "Higienista Dental (RDH)",
        salaryP25: 80000,
        salaryP50: 95000,
        salaryP75: 115000,
        yearsExperience: "2–5 years",
        esYearsExperience: "2–5 años",
        certifications: [
          "California RDH license (required)",
          "Local Anesthesia permit (required at most FQHCs)",
          "Nitrous Oxide permit (strongly preferred)",
          "Tobacco Cessation Counselor (preferred)",
        ],
        esCertifications: [
          "Licencia RDH de California (requerida)",
          "Permiso de Anestesia Local (requerido en la mayoría de FQHCs)",
          "Permiso de Óxido Nitroso (fuertemente preferido)",
          "Consejero de Cesación Tabáquica (preferido)",
        ],
        keySkills: [
          "Full-mouth periodontal assessment & SRP",
          "Denti-Cal procedure coding & documentation",
          "Patient oral hygiene education",
          "Pediatric sealants & fluoride varnish",
          "Motivational interviewing for behavior change",
        ],
        esKeySkills: [
          "Evaluación periodontal de boca completa y SRP",
          "Codificación de procedimientos Denti-Cal y documentación",
          "Educación de higiene oral del paciente",
          "Selladores pediátricos y barniz de flúor",
          "Entrevista motivacional para cambio de comportamiento",
        ],
        programs: ["Denti-Cal", "CHDP", "Head Start oral health"],
      },
      {
        roleId: "dentist",
        title: "Dentist (DDS/DMD)",
        esTitle: "Dentista (DDS/DMD)",
        salaryP25: 155000,
        salaryP50: 190000,
        salaryP75: 225000,
        yearsExperience: "3–10 years",
        esYearsExperience: "3–10 años",
        certifications: [
          "DDS or DMD from CODA-accredited program",
          "Active California dental license",
          "DEA registration",
          "NHSC loan repayment eligible (up to $80K/2yr)",
        ],
        esCertifications: [
          "DDS o DMD de programa acreditado por CODA",
          "Licencia dental activa de California",
          "Registro DEA",
          "Elegible para pago de préstamos NHSC (hasta $80K/2 años)",
        ],
        keySkills: [
          "Full-scope general dentistry",
          "Denti-Cal billing & prior authorization",
          "FQHC PPS dental reimbursement",
          "Oral-systemic health integration",
          "Dental team supervision (hygienists, DAs, EDDAs)",
        ],
        esKeySkills: [
          "Odontología general de alcance completo",
          "Facturación Denti-Cal y autorización previa",
          "Reembolso dental PPS de FQHC",
          "Integración de salud oral-sistémica",
          "Supervisión de equipo dental (higienistas, DAs, EDDAs)",
        ],
        programs: ["Denti-Cal", "NHSC", "Virtual Dental Home"],
      },
      {
        roleId: "dental_director",
        title: "Dental Director",
        esTitle: "Director(a) Dental",
        salaryP25: 175000,
        salaryP50: 220000,
        salaryP75: 265000,
        yearsExperience: "10+ years",
        esYearsExperience: "10+ años",
        certifications: [
          "DDS/DMD with active CA license",
          "DEA registration",
          "AAPHD Fellowship (preferred)",
          "Healthcare leadership training (preferred)",
        ],
        esCertifications: [
          "DDS/DMD con licencia activa de CA",
          "Registro DEA",
          "Fellowship AAPHD (preferido)",
          "Capacitación en liderazgo de salud (preferido)",
        ],
        keySkills: [
          "Multi-site dental program management",
          "Clinical quality metrics & peer review",
          "Denti-Cal & PPS revenue optimization",
          "HRSA scope-of-service changes",
          "Dental team recruitment, retention & development",
          "Budget management & capital planning (operatory buildout)",
        ],
        esKeySkills: [
          "Gestión de programas dentales multi-sitio",
          "Métricas de calidad clínica y revisión de pares",
          "Optimización de ingresos Denti-Cal y PPS",
          "Cambios en alcance de servicios HRSA",
          "Reclutamiento, retención y desarrollo de equipo dental",
          "Gestión de presupuesto y planificación de capital (construcción de consultorios)",
        ],
        programs: ["Denti-Cal", "NHSC", "HRSA Oral Health Program", "Virtual Dental Home"],
      },
    ],
  },
];

// Helper: get pathway by ID
export function getPathwayById(id: string): CareerPathway | undefined {
  return CAREER_PATHWAYS.find((p) => p.id === id);
}

// Map assessment roleIds to pathway roleIds when they share a level
const ROLE_ALIASES: Record<string, string> = {
  hr_manager: "accountant", // HR Manager shares Level 2 with Accountant in back-office track
};

// Helper: find which pathway contains a given roleId
export function getPathwayForRole(roleId: string): CareerPathway | undefined {
  const lookupId = ROLE_ALIASES[roleId] ?? roleId;
  return CAREER_PATHWAYS.find((p) =>
    p.levels.some((l) => l.roleId === lookupId)
  );
}

// Helper: apply regional multiplier to salary
export function adjustSalary(baseSalary: number, multiplier: number): number {
  return Math.round(baseSalary * multiplier / 1000) * 1000;
}
