// Career pathway data for California FQHCs
// 5 career tracks with 4 levels each, CA-specific salary ranges and certifications

export interface CareerLevel {
  roleId: string;
  title: string;
  esTitle: string;
  salaryP25: number;
  salaryP50: number;
  salaryP75: number;
  yearsExperience: string;
  esYearsExperience: string;
  certifications: string[];
  esCertifications: string[];
  keySkills: string[];
  esKeySkills: string[];
  programs: string[];
}

export interface CareerPathway {
  id: string;
  name: string;
  esName: string;
  description: string;
  esDescription: string;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
  levels: CareerLevel[];
}

export interface RegionalMultiplier {
  region: string;
  esRegion: string;
  multiplier: number;
  description: string;
  esDescription: string;
}

// California regional salary multipliers based on cost-of-living differences
export const REGIONAL_MULTIPLIERS: RegionalMultiplier[] = [
  {
    region: "SF Bay Area",
    esRegion: "Área de la Bahía de SF",
    multiplier: 1.15,
    description: "Highest cost of living in CA. FQHCs compete with tech for talent.",
    esDescription: "Mayor costo de vida en CA. Los FQHCs compiten con la tecnología por talento.",
  },
  {
    region: "Los Angeles",
    esRegion: "Los Ángeles",
    multiplier: 1.08,
    description: "Large FQHC market. 60+ health centers across LA County.",
    esDescription: "Gran mercado de FQHCs. Más de 60 centros de salud en el condado de LA.",
  },
  {
    region: "San Diego",
    esRegion: "San Diego",
    multiplier: 1.05,
    description: "Growing FQHC network. Bilingual Spanish strongly valued.",
    esDescription: "Red creciente de FQHCs. Se valora mucho el bilingüismo en español.",
  },
  {
    region: "Central Coast",
    esRegion: "Costa Central",
    multiplier: 1.02,
    description: "Santa Barbara, San Luis Obispo, Monterey. Rural access challenges.",
    esDescription: "Santa Bárbara, San Luis Obispo, Monterey. Desafíos de acceso rural.",
  },
  {
    region: "Sacramento",
    esRegion: "Sacramento",
    multiplier: 1.0,
    description: "State capital baseline. Strong government health programs.",
    esDescription: "Base de la capital estatal. Fuertes programas gubernamentales de salud.",
  },
  {
    region: "Inland Empire",
    esRegion: "Inland Empire",
    multiplier: 0.95,
    description: "Riverside & San Bernardino. High demand, underserved communities.",
    esDescription: "Riverside y San Bernardino. Alta demanda, comunidades desatendidas.",
  },
  {
    region: "Central Valley",
    esRegion: "Valle Central",
    multiplier: 0.92,
    description: "Fresno, Bakersfield, Stockton. Critical shortage areas. Bilingual essential.",
    esDescription: "Fresno, Bakersfield, Stockton. Áreas de escasez crítica. Bilingüismo esencial.",
  },
  {
    region: "North State",
    esRegion: "Norte del Estado",
    multiplier: 0.9,
    description: "Redding, Chico. Rural FQHCs with NHSC loan repayment eligibility.",
    esDescription: "Redding, Chico. FQHCs rurales con elegibilidad de pago de préstamos NHSC.",
  },
  {
    region: "North Coast",
    esRegion: "Costa Norte",
    multiplier: 0.88,
    description: "Humboldt, Mendocino. Most remote, tribal health partnerships.",
    esDescription: "Humboldt, Mendocino. Más remotos, alianzas de salud tribal.",
  },
];

export const CAREER_PATHWAYS: CareerPathway[] = [
  {
    id: "community-health",
    name: "Community Health",
    esName: "Salud Comunitaria",
    description: "From frontline community work to directing programs that serve thousands.",
    esDescription: "Del trabajo comunitario en primera línea a dirigir programas que atienden a miles.",
    icon: "Heart",
    color: "teal",
    levels: [
      {
        roleId: "chw",
        title: "Community Health Worker",
        esTitle: "Promotor(a) de Salud",
        salaryP25: 38000,
        salaryP50: 45000,
        salaryP75: 55000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["CA CHW Certificate (CDPH)"],
        esCertifications: ["Certificado de CHW de California (CDPH)"],
        keySkills: [
          "Community outreach",
          "Health education",
          "Motivational interviewing",
          "Bilingual communication",
          "Resource navigation",
        ],
        esKeySkills: [
          "Alcance comunitario",
          "Educación en salud",
          "Entrevista motivacional",
          "Comunicación bilingüe",
          "Navegación de recursos",
        ],
        programs: ["CalAIM ECM", "Medi-Cal", "WIC"],
      },
      {
        roleId: "care-coordinator",
        title: "Care Coordinator",
        esTitle: "Coordinador(a) de Cuidado",
        salaryP25: 45000,
        salaryP50: 55000,
        salaryP75: 65000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CCM (optional)", "CalAIM ECM Training"],
        esCertifications: ["CCM (opcional)", "Capacitación CalAIM ECM"],
        keySkills: [
          "Care plan development",
          "Multi-provider coordination",
          "EHR documentation (OCHIN Epic)",
          "Patient advocacy",
          "Data tracking & reporting",
        ],
        esKeySkills: [
          "Desarrollo de planes de cuidado",
          "Coordinación multi-proveedor",
          "Documentación EHR (OCHIN Epic)",
          "Defensa del paciente",
          "Seguimiento de datos e informes",
        ],
        programs: ["CalAIM ECM/CCM", "Medi-Cal Managed Care", "HEDIS measures"],
      },
      {
        roleId: "program-manager",
        title: "Program Manager",
        esTitle: "Gerente de Programa",
        salaryP25: 65000,
        salaryP50: 78000,
        salaryP75: 90000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["PMP (optional)", "CCM"],
        esCertifications: ["PMP (opcional)", "CCM"],
        keySkills: [
          "Team supervision",
          "Grant writing & compliance",
          "Program evaluation",
          "Budget management",
          "Stakeholder engagement",
        ],
        esKeySkills: [
          "Supervisión de equipo",
          "Redacción de subvenciones y cumplimiento",
          "Evaluación de programas",
          "Gestión de presupuesto",
          "Participación de partes interesadas",
        ],
        programs: ["HRSA UDS reporting", "CalAIM", "340B"],
      },
      {
        roleId: "director-community",
        title: "Director of Community Programs",
        esTitle: "Director(a) de Programas Comunitarios",
        salaryP25: 90000,
        salaryP50: 110000,
        salaryP75: 130000,
        yearsExperience: "7+ years",
        esYearsExperience: "7+ años",
        certifications: ["MPH or MPA (preferred)"],
        esCertifications: ["MPH o MPA (preferido)"],
        keySkills: [
          "Strategic planning",
          "Cross-department leadership",
          "Board reporting",
          "Community partnerships",
          "Policy advocacy",
        ],
        esKeySkills: [
          "Planificación estratégica",
          "Liderazgo interdepartamental",
          "Informes a la junta",
          "Alianzas comunitarias",
          "Defensa de políticas",
        ],
        programs: ["FQHC look-alike designation", "PCMH", "ACO partnerships"],
      },
    ],
  },
  {
    id: "clinical-operations",
    name: "Clinical Operations",
    esName: "Operaciones Clínicas",
    description: "From medical assisting to leading clinical teams and operations.",
    esDescription: "De asistencia médica a liderar equipos y operaciones clínicas.",
    icon: "Stethoscope",
    color: "blue",
    levels: [
      {
        roleId: "medical-assistant",
        title: "Medical Assistant",
        esTitle: "Asistente Médico",
        salaryP25: 36000,
        salaryP50: 42000,
        salaryP75: 50000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["CMA (AAMA) or RMA", "BLS/CPR"],
        esCertifications: ["CMA (AAMA) o RMA", "BLS/CPR"],
        keySkills: [
          "Vitals & patient intake",
          "EHR data entry (OCHIN Epic)",
          "Phlebotomy",
          "Bilingual patient communication",
          "Exam room preparation",
        ],
        esKeySkills: [
          "Signos vitales e ingreso de pacientes",
          "Entrada de datos EHR (OCHIN Epic)",
          "Flebotomía",
          "Comunicación bilingüe con pacientes",
          "Preparación de sala de examen",
        ],
        programs: ["PCMH workflows", "Immunization tracking"],
      },
      {
        roleId: "lead-ma",
        title: "Lead Medical Assistant",
        esTitle: "Asistente Médico Líder",
        salaryP25: 42000,
        salaryP50: 50000,
        salaryP75: 58000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CMA", "BLS", "OCHIN Epic proficiency"],
        esCertifications: ["CMA", "BLS", "Competencia en OCHIN Epic"],
        keySkills: [
          "MA team scheduling",
          "Training new MAs",
          "Inventory management",
          "Quality improvement",
          "Provider support coordination",
        ],
        esKeySkills: [
          "Programación del equipo de MA",
          "Capacitación de nuevos MAs",
          "Gestión de inventario",
          "Mejora de calidad",
          "Coordinación de apoyo a proveedores",
        ],
        programs: ["HEDIS measures", "Patient-Centered Medical Home"],
      },
      {
        roleId: "clinical-ops-supervisor",
        title: "Clinical Operations Supervisor",
        esTitle: "Supervisor(a) de Operaciones Clínicas",
        salaryP25: 55000,
        salaryP50: 65000,
        salaryP75: 75000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["Healthcare management certificate (optional)"],
        esCertifications: ["Certificado de gestión sanitaria (opcional)"],
        keySkills: [
          "Workflow optimization",
          "Staff performance management",
          "Regulatory compliance (OSHA, HIPAA)",
          "Patient throughput analysis",
          "Cross-site coordination",
        ],
        esKeySkills: [
          "Optimización de flujo de trabajo",
          "Gestión del desempeño del personal",
          "Cumplimiento regulatorio (OSHA, HIPAA)",
          "Análisis de flujo de pacientes",
          "Coordinación entre sitios",
        ],
        programs: ["UDS reporting", "Joint Commission prep"],
      },
      {
        roleId: "director-clinical-ops",
        title: "Director of Clinical Operations",
        esTitle: "Director(a) de Operaciones Clínicas",
        salaryP25: 80000,
        salaryP50: 100000,
        salaryP75: 120000,
        yearsExperience: "7+ years",
        esYearsExperience: "7+ años",
        certifications: ["MHA or MBA (preferred)"],
        esCertifications: ["MHA o MBA (preferido)"],
        keySkills: [
          "Multi-site management",
          "Strategic capacity planning",
          "EHR system optimization",
          "Provider recruitment strategy",
          "Board-level reporting",
        ],
        esKeySkills: [
          "Gestión multi-sitio",
          "Planificación estratégica de capacidad",
          "Optimización del sistema EHR",
          "Estrategia de reclutamiento de proveedores",
          "Informes a nivel de junta",
        ],
        programs: ["FQHC compliance (HRSA)", "340B administration"],
      },
    ],
  },
  {
    id: "behavioral-health",
    name: "Behavioral Health",
    esName: "Salud Conductual",
    description: "From behavioral health support to leading integrated care programs.",
    esDescription: "Del apoyo en salud conductual a liderar programas de cuidado integrado.",
    icon: "Brain",
    color: "purple",
    levels: [
      {
        roleId: "bh-technician",
        title: "Behavioral Health Technician",
        esTitle: "Técnico de Salud Conductual",
        salaryP25: 35000,
        salaryP50: 42000,
        salaryP75: 48000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["BLS/CPR", "Trauma-Informed Care training"],
        esCertifications: ["BLS/CPR", "Capacitación en cuidado informado por trauma"],
        keySkills: [
          "Crisis de-escalation",
          "Group facilitation",
          "Screening tools (PHQ-9, GAD-7)",
          "Safety planning",
          "Bilingual support",
        ],
        esKeySkills: [
          "Desescalada de crisis",
          "Facilitación de grupos",
          "Herramientas de detección (PHQ-9, GAD-7)",
          "Planificación de seguridad",
          "Apoyo bilingüe",
        ],
        programs: ["BH-ASO", "SBIRT screening"],
      },
      {
        roleId: "behavioral-health",
        title: "Behavioral Health Specialist",
        esTitle: "Especialista en Salud Conductual",
        salaryP25: 55000,
        salaryP50: 70000,
        salaryP75: 85000,
        yearsExperience: "2–3 years",
        esYearsExperience: "2–3 años",
        certifications: ["AMFT or APCC (CA BBS)", "Motivational Interviewing"],
        esCertifications: ["AMFT o APCC (CA BBS)", "Entrevista Motivacional"],
        keySkills: [
          "Individual & group therapy",
          "Integrated care model",
          "Clinical documentation",
          "Warm handoffs with PCPs",
          "Cultural competency",
        ],
        esKeySkills: [
          "Terapia individual y grupal",
          "Modelo de cuidado integrado",
          "Documentación clínica",
          "Transiciones cálidas con PCPs",
          "Competencia cultural",
        ],
        programs: ["CalAIM BH services", "Medi-Cal BH carve-in"],
      },
      {
        roleId: "licensed-therapist",
        title: "Licensed Therapist (LCSW/LMFT)",
        esTitle: "Terapeuta con Licencia (LCSW/LMFT)",
        salaryP25: 70000,
        salaryP50: 85000,
        salaryP75: 100000,
        yearsExperience: "4–6 years",
        esYearsExperience: "4–6 años",
        certifications: ["LCSW or LMFT (CA BBS)", "NHSC eligible"],
        esCertifications: ["LCSW o LMFT (CA BBS)", "Elegible para NHSC"],
        keySkills: [
          "Clinical supervision of pre-licensed staff",
          "Evidence-based treatment (CBT, DBT, MI)",
          "Complex case consultation",
          "Community referral network",
          "Telehealth delivery",
        ],
        esKeySkills: [
          "Supervisión clínica de personal pre-licenciado",
          "Tratamiento basado en evidencia (CBT, DBT, MI)",
          "Consulta de casos complejos",
          "Red de referencia comunitaria",
          "Entrega de telesalud",
        ],
        programs: ["NHSC Loan Repayment ($50-75K)", "CalAIM ECM BH"],
      },
      {
        roleId: "bh-director",
        title: "Behavioral Health Director",
        esTitle: "Director(a) de Salud Conductual",
        salaryP25: 95000,
        salaryP50: 118000,
        salaryP75: 140000,
        yearsExperience: "8+ years",
        esYearsExperience: "8+ años",
        certifications: ["LCSW/LMFT", "Clinical Supervisor credential"],
        esCertifications: ["LCSW/LMFT", "Credencial de Supervisor Clínico"],
        keySkills: [
          "Department budget management",
          "Integrated BH program development",
          "Staff recruitment & retention",
          "Outcomes measurement",
          "Payer contract negotiation",
        ],
        esKeySkills: [
          "Gestión de presupuesto departamental",
          "Desarrollo de programas BH integrados",
          "Reclutamiento y retención de personal",
          "Medición de resultados",
          "Negociación de contratos con pagadores",
        ],
        programs: ["CCBHC designation", "Medi-Cal BH managed care"],
      },
    ],
  },
  {
    id: "revenue-admin",
    name: "Revenue & Administration",
    esName: "Ingresos y Administración",
    description: "From front desk to financial leadership — the business backbone of FQHCs.",
    esDescription: "De la recepción al liderazgo financiero — la columna vertebral de los FQHCs.",
    icon: "DollarSign",
    color: "amber",
    levels: [
      {
        roleId: "patient-services",
        title: "Patient Services Representative",
        esTitle: "Representante de Servicios al Paciente",
        salaryP25: 36000,
        salaryP50: 42000,
        salaryP75: 48000,
        yearsExperience: "Entry level",
        esYearsExperience: "Nivel de entrada",
        certifications: ["OCHIN Epic front desk training"],
        esCertifications: ["Capacitación de recepción OCHIN Epic"],
        keySkills: [
          "Patient registration",
          "Insurance verification (Medi-Cal, Medicare)",
          "Appointment scheduling",
          "Sliding fee scale enrollment",
          "Bilingual front desk",
        ],
        esKeySkills: [
          "Registro de pacientes",
          "Verificación de seguros (Medi-Cal, Medicare)",
          "Programación de citas",
          "Inscripción en escala de tarifas variables",
          "Recepción bilingüe",
        ],
        programs: ["Sliding Fee Scale", "Medi-Cal eligibility"],
      },
      {
        roleId: "revenue-cycle",
        title: "Revenue Cycle Specialist",
        esTitle: "Especialista en Ciclo de Ingresos",
        salaryP25: 50000,
        salaryP50: 60000,
        salaryP75: 72000,
        yearsExperience: "1–2 years",
        esYearsExperience: "1–2 años",
        certifications: ["CPC (AAPC)", "OCHIN Epic Certification"],
        esCertifications: ["CPC (AAPC)", "Certificación OCHIN Epic"],
        keySkills: [
          "Medical coding (ICD-10, CPT)",
          "Claims submission & denial management",
          "PPS rate optimization",
          "A/R follow-up",
          "Compliance auditing",
        ],
        esKeySkills: [
          "Codificación médica (ICD-10, CPT)",
          "Envío de reclamos y gestión de denegaciones",
          "Optimización de tarifas PPS",
          "Seguimiento de cuentas por cobrar",
          "Auditoría de cumplimiento",
        ],
        programs: ["FQHC PPS reimbursement", "340B"],
      },
      {
        roleId: "revenue-manager",
        title: "Revenue Cycle Manager",
        esTitle: "Gerente de Ciclo de Ingresos",
        salaryP25: 65000,
        salaryP50: 78000,
        salaryP75: 90000,
        yearsExperience: "3–5 years",
        esYearsExperience: "3–5 años",
        certifications: ["CPC", "CHFP (optional)"],
        esCertifications: ["CPC", "CHFP (opcional)"],
        keySkills: [
          "Team management",
          "Revenue forecasting",
          "Payer contract analysis",
          "Process improvement",
          "EHR revenue module administration",
        ],
        esKeySkills: [
          "Gestión de equipo",
          "Pronóstico de ingresos",
          "Análisis de contratos con pagadores",
          "Mejora de procesos",
          "Administración del módulo de ingresos EHR",
        ],
        programs: ["UDS financial reporting", "FQHC Cost Report"],
      },
      {
        roleId: "director-finance",
        title: "Director of Finance / CFO",
        esTitle: "Director(a) de Finanzas / CFO",
        salaryP25: 100000,
        salaryP50: 130000,
        salaryP75: 160000,
        yearsExperience: "8+ years",
        esYearsExperience: "8+ años",
        certifications: ["CPA or MBA/MHA (preferred)"],
        esCertifications: ["CPA o MBA/MHA (preferido)"],
        keySkills: [
          "Financial strategy & planning",
          "Grant financial management (HRSA)",
          "Board financial reporting",
          "Audit coordination",
          "Multi-site financial operations",
        ],
        esKeySkills: [
          "Estrategia y planificación financiera",
          "Gestión financiera de subvenciones (HRSA)",
          "Informes financieros a la junta",
          "Coordinación de auditorías",
          "Operaciones financieras multi-sitio",
        ],
        programs: ["HRSA grant compliance", "340B optimization", "FQHC Cost Report"],
      },
    ],
  },
  {
    id: "nursing",
    name: "Nursing & Clinical Leadership",
    esName: "Enfermería y Liderazgo Clínico",
    description: "From bedside nursing to leading entire clinical organizations.",
    esDescription: "De enfermería clínica a liderar organizaciones clínicas completas.",
    icon: "Activity",
    color: "rose",
    levels: [
      {
        roleId: "rn",
        title: "Registered Nurse (RN)",
        esTitle: "Enfermero(a) Registrado(a) (RN)",
        salaryP25: 85000,
        salaryP50: 105000,
        salaryP75: 125000,
        yearsExperience: "Entry level (BSN)",
        esYearsExperience: "Nivel de entrada (BSN)",
        certifications: ["RN License (CA BRN)", "BLS/CPR", "BSN (preferred)"],
        esCertifications: ["Licencia RN (CA BRN)", "BLS/CPR", "BSN (preferido)"],
        keySkills: [
          "Patient assessment & triage",
          "Medication administration",
          "Care coordination",
          "EHR documentation (OCHIN Epic)",
          "Patient education",
        ],
        esKeySkills: [
          "Evaluación y triaje de pacientes",
          "Administración de medicamentos",
          "Coordinación de cuidado",
          "Documentación EHR (OCHIN Epic)",
          "Educación del paciente",
        ],
        programs: ["NHSC Loan Repayment", "CalAIM clinical programs"],
      },
      {
        roleId: "charge-nurse",
        title: "Charge Nurse",
        esTitle: "Enfermero(a) a Cargo",
        salaryP25: 95000,
        salaryP50: 115000,
        salaryP75: 140000,
        yearsExperience: "2–3 years",
        esYearsExperience: "2–3 años",
        certifications: ["BSN", "BLS/ACLS", "OCHIN Epic proficiency"],
        esCertifications: ["BSN", "BLS/ACLS", "Competencia en OCHIN Epic"],
        keySkills: [
          "Shift management",
          "Clinical staff scheduling",
          "Quality metric tracking",
          "New nurse mentoring",
          "Emergency response leadership",
        ],
        esKeySkills: [
          "Gestión de turnos",
          "Programación de personal clínico",
          "Seguimiento de métricas de calidad",
          "Mentoría de enfermeros nuevos",
          "Liderazgo de respuesta a emergencias",
        ],
        programs: ["HEDIS quality measures", "Patient safety protocols"],
      },
      {
        roleId: "nurse-manager",
        title: "Nurse Manager",
        esTitle: "Gerente de Enfermería",
        salaryP25: 110000,
        salaryP50: 130000,
        salaryP75: 155000,
        yearsExperience: "5–7 years",
        esYearsExperience: "5–7 años",
        certifications: ["MSN (preferred)", "Nurse Executive certification (optional)"],
        esCertifications: ["MSN (preferido)", "Certificación de ejecutivo de enfermería (opcional)"],
        keySkills: [
          "Department budget management",
          "Staff recruitment & retention",
          "Clinical protocol development",
          "Interdisciplinary team leadership",
          "Performance improvement",
        ],
        esKeySkills: [
          "Gestión de presupuesto departamental",
          "Reclutamiento y retención de personal",
          "Desarrollo de protocolos clínicos",
          "Liderazgo de equipo interdisciplinario",
          "Mejora del desempeño",
        ],
        programs: ["Joint Commission readiness", "PCMH standards"],
      },
      {
        roleId: "cno",
        title: "Chief Nursing Officer (CNO)",
        esTitle: "Director(a) de Enfermería (CNO)",
        salaryP25: 130000,
        salaryP50: 165000,
        salaryP75: 200000,
        yearsExperience: "10+ years",
        esYearsExperience: "10+ años",
        certifications: ["DNP or MSN", "NEA-BC (optional)"],
        esCertifications: ["DNP o MSN", "NEA-BC (opcional)"],
        keySkills: [
          "Organizational nursing strategy",
          "C-suite leadership",
          "Clinical quality & safety oversight",
          "Workforce planning",
          "Community health partnerships",
        ],
        esKeySkills: [
          "Estrategia organizacional de enfermería",
          "Liderazgo de nivel ejecutivo",
          "Supervisión de calidad y seguridad clínica",
          "Planificación de fuerza laboral",
          "Alianzas de salud comunitaria",
        ],
        programs: ["HRSA strategic planning", "ACO/VBC models"],
      },
    ],
  },
];

// Helper: get pathway by ID
export function getPathwayById(id: string): CareerPathway | undefined {
  return CAREER_PATHWAYS.find((p) => p.id === id);
}

// Helper: find which pathway contains a given roleId
export function getPathwayForRole(roleId: string): CareerPathway | undefined {
  return CAREER_PATHWAYS.find((p) =>
    p.levels.some((l) => l.roleId === roleId)
  );
}

// Helper: apply regional multiplier to salary
export function adjustSalary(baseSalary: number, multiplier: number): number {
  return Math.round(baseSalary * multiplier / 1000) * 1000;
}
